### ISSUE TITLE
Extend action to grant permission for user link to a company

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#104]
Extend work done in #103 to grant the permission to a user **in** a company. This will be required for permissions that are given to users when they are logged in to a company.

**Comment by CarlosNZ** [comment]
Can I just clarify what this issue is requiring, I'm a bit confused?

Are we extending the existing `grantPermissions` Action so that it can grant a permission name to a `orgId` as well as a `userId`? (Currently just does user)

Or does it mean something else?
