### ISSUE TITLE
Log-out endpoint

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#106]

**Comment by CarlosNZ** [comment]
We don't need a back-end endpoint for logging out, do we? Just need to clear local JWT in front-end, right?

In which case, this is pretty much done in [front end #115](https://github.com/openmsupply/application-manager-web-app/pull/144)

**Comment by nmadruga** [comment]
Thanks. I wasn't sure if we would need it. Closing this one. : )
