### ISSUE TITLE
Update "Join Company" template to display dynamic labels (in infoText plugin) (Final Touches)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#124]
This could become another plugin (that contains both: the input and the label - e.g. to display a search company) but just so we can update the `textInfo` to display dynamic label for now we decided to work with this option first and migrate to a proper single plugin later.

**Comment by nmadruga** [comment]
Please add more 2 or 3 companies to the system for testing.

**Comment by CarlosNZ** [comment]
This issue needs #124 to be done (and agreed how it should work) first.

**Comment by CarlosNZ** [comment]
Would also suggest adding at least one dynamic "options" list for the dropdownChoice plugin, maybe with an API call to really test it out properly.

**Comment by nmadruga** [comment]
Not sure if done (or needed). I'll  close as invalid for now.
