### ISSUE TITLE
Edit the review schema to consider changes on review process

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#131]

**Comment by andreievg** [comment]
Schema was changes to accomodate 'review' process miss-alignment between our designs and specs from Valerio.

The main differences:
* Reviewer does not suggest changes, they only identify conformity or non-conformity, with comment
* Consolidator agrees or disagrees, and reviewer has to make the changes
* Consolidator decides to send LOQ or suggest non conformity
* Similar logic with Consolidator to Consolidator interactions

Revised schema diagram `Review revised 06-12` in drive (date might change)

![Review revised 06-12](https://user-images.githubusercontent.com/26194949/101300044-18abdc00-3899-11eb-95ae-6bc058705a41.png)

There is also a diagram to show how schema of Review is applied in action `Consolidation Flow with Schema Example Complex`

As part of this issue, I'll consider adding action for review_status_history (similar to application), or add as new issue

**Comment by andreievg** [comment]
Current and proposed triggers

'onApplicationCreate'
onApplicationSubmit'
'onApplicationSave'
'onApplicationWithdrawn'
'onReviewStart' -> 'onReviewCreate'
'onReviewEditComment'
'onReviewSave' -> 'onReviewSubmit'
'onReviewAssign'
'onApprovalSubmit'
'onScheduleTime'
'Processing', 'Error'

**Comment by CarlosNZ** [comment]
> Current and proposed triggers
> 
> 'onApplicationCreate'
> onApplicationSubmit'
> 'onApplicationSave'
> 'onApplicationWithdrawn'
> 'onReviewStart' -> 'onReviewCreate'
> 'onReviewEditComment'
> 'onReviewSave' -> 'onReviewSubmit'
> 'onReviewAssign'
> 'onApprovalSubmit'
> 'onScheduleTime'
> 'Processing', 'Error'

Yeah, there is a trigger enum defined in `16_application.sql`

**Comment by andreievg** [comment]
that's from there

**Comment by CarlosNZ** [comment]
Cool, will probably be useful to have a VIEW table or two to collate a lot of this info, but can think about what it should have once we've got the schema in place.
