### ISSUE TITLE
Evaluator: new operator -- stringSubstitution

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#158]
Child nodes:
0: String with %1, %2 parameters embedded
1-n: values to be substituted into %1, %2

Will be useful for creating more complex message strings for start and end of template, etc. Could be done with "CONCAT", but the queries would get ridiculous.

--- 
Just putting this here now so I have it for later:

Regex for matching parameters: `(?<![\\])%([\d]+)`
- ~~Allows `$` or `%` prefix~~
- ~~Ignores literal % (if you prefix them with `\` in string)~~
- Captures the number part in Group for further processing

**Comment by andreievg** [comment]
In the docs from this pr: https://github.com/openmsupply/application-manager-server/pull/161, there is suggestion of dollar sign, maybe just percentage sign ?

**Comment by CarlosNZ** [comment]
> In the docs from this pr: #161, there is suggestion of dollar sign, maybe just percentage sign ?

Sure, is that more "standard"? Just noticed that SQL uses $1. Was just thinking that because we'll probably write a regex to find the parameters, it would be pretty simple to allow both options.

Question: do you think ordering should follow strict numerical order, or just the order in the string? So if the string has `"First name: %2, Last name: %1"`, do we replace them in inverse order that the values are supplied, or just in the order it finds the parameters and ignore the actual numbers?

I only ask because matching the numerical order seems more "correct", but quite a bit more complex code-wise, so just wondering if you think it's worth it?

**Comment by andreievg** [comment]
I think numeric value after the '%' should match child index. Btw in implementation I would just go through each child and do global replace of %{childnumber} (regex should make sure no other digits after %{childnumber})

The only reason for not wanting $ is cause $1 might be a price whereas percentage always follows a number
