### ISSUE TITLE
Default Actions -- create GraphQL fragment?

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#184]
First step: Make a list (create a diagram) of all Actions that happen for every application type.

Second step: Write createAction mutations for the above as GraphQL fragment.

Third step: Add above fragment ton existing createTemplate mutations

---

### onApplicationCreate
- IncrementStage (also updates status)

### onApplicationSubmit
- Change Status (to Submitted)
- ReviewAssignmentGenerate (still to be worked out how it will work -- might be "global" rather than template-based)

### onReviewAssign
- TBD

### onReviewCreate
- Change (Review) Status

### onReviewSubmit
- Change (Review) Status
- ReviewAssignmentGenerate (TBD, as above)
- Check if approved and on Final review stage, if so ChangeOutcome, etc...

**Comment by CarlosNZ** [comment]
Need to wait until OnReview triggers/actions have been implemented (and maybe Consolidate?)

**Comment by andreievg** [comment]
actually, this would require a bit more thought.

* dont' think you can use fragments for mutations
* if you could we would need to concat the fragment definition to the end of each query (apollo client does this automatically)
* would be a bit harder if we added custom actions to know next sequence number (but I guess we can start them at like 101)

**Comment by CarlosNZ** [comment]
>     * dont' think you can use fragments for mutations

You can -- currently have some in front-end, `createApplication.mutation.ts` for example.

>     * would be a bit harder if we added custom actions to know next sequence number (but I guess we can start them at like 101)

Yeah, exactly, just start at a high number for later ones, or make them asynchronous (no sequence number) where possible.

**Comment by andreievg** [comment]
> You can -- currently have some in front-end, createApplication.mutation.ts for example.

ahh ok, i see what you mean (it's not quite a fragment though).

So we would define a new query for mutation (with template id). And then concat it to the end of each of the template generation queries (replacing template id with the new template id), right ?

Would still like to have core action template (that can be copied when creating new template on front end (otherwise would need to share this core mutation with front end code, or try do this mutation on back end when new template is generated)

**Comment by CarlosNZ** [comment]
> Yeah, exactly, just start at a high number for later ones, or make them asynchronous (no sequence number) where possible.

Or, we can make the Fragment sequence values use negative numbers, so any additional Actions can start at 1 with no problems ;)

**Comment by CarlosNZ** [comment]
Will do this quickly now. As discussed with @andreievg will do:
- take the createActions mutation query from "03_template_E_coreActions" and export it as a variable
- import this into other template .js files and insert into mutation using template literal `${substitution}`
