### ISSUE TITLE
Insert different levels of reviews in different stages of ReviewTest template

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#188]

**Comment by nmadruga** [comment]
We do need to add the information of how many level of review are required in each stage of the template.
Quick discussing with @CarlosNZ we see the need of adding one `review_decision` per review, regardless if it is a consolidation review or not. In the case that there is only one level of review => When the reviewer submits the review, the `review_decision` should also get created (in the same mutation) and since there is only one level of review - this should be used to change the application stage (in case of approval). It seems reasonable to me that, in order to change the application stage, this reviewer needs to have consolidator permission on that stage+template. 
In the UI we can deal as if - review is completed as usual. Then if the user has `consolidation` permission & is the final review level & all reviews have been finished (there may be a case that review is done by 2 reviewers), we would shouw the user the **Consolidation step** where they confirm the `review_decision` to be send back to the Applicant.

**Comment by CarlosNZ** [comment]
Also I would add that with each review level (in the template) we should also have a "name". So names like "review", "initial review", "consolidate", etc. would be template-specific and not hard-coded into the system, similar to what we do with Stages. 

That way, the UI doesn't have to do any logic as to what heading/page names to show, it would just get `currentReviewLevel.name`, or something like that.

**Comment by CarlosNZ** [comment]
Andrei's response in Telegram chat for example of how this is represented: 

> With current thinking:
>
> Stage 1:
> 
> template_permission (restrictions: `{ stage: 1, lvl: 1, canMakeOverallDecision: true }`) -> permission_name (name: "Screener") -> permission_policy (type: "Review, name: "BaseReviewer")
> 
> Stage 2:
> 
> template_permission (restrictions: `{ stage: 2, lvl: 1, section: 1 }`) -> permission_name (name: "Assessor of First Section") -> permission_policy (type: "Review", name: "BaseReviewer")
> 
> template_permission (restrictions: `{ stage: 2, lvl: 1, section: 2 }`) -> permission_name (name: "Assessoor of Second Section") -> permission_policy (type: "Review", name: "BaseReviewer")
> 
> template_permission (restrictions: `{ stage: 2, lvl: 2 }`) -> permission_name (name: "Senior Assessors") -> permission_policy (type: "Review", name: "Consolidator") <- this policy will prolly have slightly different rules to "BaseReviewer"
> 
> Stage 3 (needs a bit more thinking about):
> 
> template_permission (restrictions: `{ stage: 3, lvl: 1, section: 1, canMakeOverallDecision: true, canOverruleOverallDecision }`) -> permission_name (name: "Assessor of First Section") -> permission_policy (type: "Review", name: "Boss")
> 
> I think our conversation summary was that some of the restriction fields shoudl be moved to columns

**Comment by andreievg** [comment]
In our meeting we considered 'sections' part of the permissions as 'optional' and they becomes something like 'restrictedSectionCodes' (we don't really need to implement this atm, what it means is "what sections can be assigned' to reviewer)
