### ISSUE TITLE
Action to set review_assignments to "Not Available" when reviewer is assigned (self assigment)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#199]
Trigger: OnAssignment

- needs to check all sections are assigned, and only set "not_available" if all sections are.

**Comment by CarlosNZ** [comment]
I think this is a duplicate of #195. Didn't we have something else that needed to happen on Review submit that we were going to include in this issue?

**Comment by nmadruga** [comment]
The self-assignment should change other review_assigment statuses to NOT AVAILABLE. And for review level 1, although there might be more than one review_assigment (for the same sections/application) we don't change the status, so after the section is assigned to the reviewer there should be one ASSIGNED and others are still AVAILABLE. 

That is to simplify the re-assignment for now.
