### ISSUE TITLE
Refactor: Move Database methods to individual Action plugins

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#214]
## Problem:
The PostgresConnect module is getting quite large with many database methods. Turns out that most of these are specific to an Action plugin and not used elsewhere.
But a few are used in multiple places, in which case making small modifications to it can inadvertently break things elsewhere, which has almost happened on a few occasions. And there's no easy way to tell which methods are only used once (in which case they can be modified without consequence) and which ones are common across multiple actions/modules. I can see this becoming more and more of a problem going forward.

## Suggested solution:
- Keep the multi-use ones (or ones used by Triggers processing module) as-is.
- The `.query` method of the passed in DBConnect object can be used by each Action to construct its own internal set of database methods that it can call. This  keeps the database methods more neatly organised and coupled to their specific Actions, which makes ongoing maintenance much easier. (I'm thinking that each plugin would have its own `database.ts` file in its `src` folder, so we can still abstract the database logic away from the main Action script)

**Comment by CarlosNZ** [comment]
I think this also makes sense for ongoing plugin development -- future plugin developers should not be messing with the postGresConnect module, so will have to write their own database methods anyway.

**Comment by andreievg** [comment]
@sworup, I won't have time to review your proposed solution for lookup table issue. So in the meantime can you please look at this one ? You can submit a PR for just one of the plugins refactor (for @CarlosNZ or @nmadruga  to check), then if it looks good, for the others

**Comment by CarlosNZ** [comment]
FYI -- my latest Action plugin (PR #137) has its database methods bundled with the plugin, in a file called `databaseMethods.ts`. @andreievg see if you think that's a good template, or if you'd prefer a slightly different structure -- then we can use that as the basic for refactoring the others.

**Comment by sworup** [comment]
@CarlosNZ I am actually working on this. 😄 
I will look into your PR code.

**Comment by CarlosNZ** [comment]
> @CarlosNZ I am actually working on this. 😄
> I will look into your PR code.

@sworup Great! Feel free to hit me up on Telegram if you have any specific questions/comments.
