### ISSUE TITLE
Change action to set assigners for each application when created/status submitted

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#263]

**Comment by CarlosNZ** [comment]
Is this covered by #264? (If so, shall we close this one?)

**Comment by nmadruga** [comment]
Yes. I think this can be closed. I'm currently investigating why the assignment for Review lvl 1+ didn't work when submitting the first lvl review as Conform, and when that's in place we should get the assignments all working as they should (appears to be a bug on the `incrementStage` action

**Comment by CarlosNZ** [comment]
> I'm currently investigating why the assignment for Review lvl 1+ didn't work when submitting the first lvl review as Conform, and when that's in place we should get the assignments all working as they should (appears to be a bug on the `incrementStage` action

Okay, I can have a look at this with you briefly if you like. I think it's probably a problem with the "Condition" expression. Be good to get to the bottom of it.
