### ISSUE TITLE
Customisable Serial number for applications

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#300]
For example: 
- Drug registrations can have serial numbers as DRxxxx
- Or application should have a 6-digit numbers serial

**Comment by CarlosNZ** [comment]
We also need to be able to generate "Professional ID" numbers, which would probably be done similarly.

Suggest creating a new Action (called "stringGenerator" ?) which will generate new strings based on parameters.

Would basically be a string substitution type of thing, but the substitutions need to be able to be either:
-- a lookup value (table, database, evaluator?)
-- random values (specify length, available chars)
-- sequential values (i.e. needs to be able to increment a value from whatever the last one was -- so do we look it up, or have some way of storing "counters")
