### ISSUE TITLE
Rename permission and template names to use org instead of company

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#308]
As per [comment](https://github.com/openmsupply/application-manager-server/pull/301#discussion_r612861098) on PR #293:

- Rename file `03_template_B_companyRegistration.js` to `03_template_B_orgRegistration.js`
- Rename file `03_template_F_companyJoin.js` to `03_template_F_joinOrganisation.js` (maybe the code too - and where it's used) 
- Rename permissions in file `02_permission_names` (and where it's used):
  - `applyCompanyRego` to `applyOrgRego`
  - `reviewCompanyRego` to `reviewOrgRego`

**Comment by CarlosNZ** [comment]
Done just before I merged #303.

**Comment by CarlosNZ** [comment]
Sorry, I didn't actually rename the permissions, just the files. Re-opening...
