### ISSUE TITLE
Snapshot improvements

### ISSUE THREAD

**Issue by andreievg** [openmsupply/application-manager-server#312]
- Make sure snapshot folder is created
- Document how to share as zip (vs test branch)
- save "files" folder as part of snapshot -- maybe with a flag `take_snapshot <snap-name> --files`, so it doesn't do it by default.

Other suggestions:
- make the "name" argument work again
- allow the "graphQLdefinitions" file to be specified, so we can have multiple "profiles" on hand:
   - one profile to export only the data related to "applications" (i.e. not templates)
   - one profile to export only "users/orgs/permissions" etc.
   - one profile to export only templates
- option to not re-initialise the database on import -- that way we can import "data" (from "applications", above), while keeping template data from `insertData`

#### Suggested usage:

For creating snapshots:
`yarn take_snapshot <name-of-snapshot> --profile <definitions-file> [--files]`

For loading snapshots:
`yarn use_snapshot <name-of-snapshot> [--no-init]`

---

If we had the above working okay, then we could use `insertData` for inserting templates/users/permissions (since they're heirarchical and the current mutations are useful and straightforward to edit) and then use a snapshot for loading data (which would be applications created using the actual app).

**Comment by nmadruga** [comment]
Clear documentation on how to share also `files` as part of snapshot recover

**Comment by nmadruga** [comment]
Step by step on how to load snapshot - should advise that the `graphql` snapshot file to upload using `yarn use_snapshot` should be called `current/graphql`

**Comment by nmadruga** [comment]
Also should't throw an error when trying to load snapshot and there isn't a folder/file named `current.graphql` just give a nice output of file not found...
![Screen Shot 2021-04-20 at 11 17 21 AM](https://user-images.githubusercontent.com/16461988/115315066-a645f380-a1ca-11eb-9a45-da5bacee32a0.png)

**Comment by CarlosNZ** [comment]
`use_snapshot` is currently only loading "current", regardless on input. Should be able to use a different named file (current should be default if not specified)

**Comment by CarlosNZ** [comment]
I'm getting this error sometimes too:
```
prettifying mutations ...
[error] database/snapshots/current.graphql: SyntaxError: Syntax Error: Expected Name, found Int "0". (1678:169)
```

The output around that location is:
```
########### applicationResponse 16 ###########
mutation { createApplicationResponse(input: {applicationResponse: {id:16,templateElementId:1022,applicationId:1,status:DRAFT,value:{text:"*<Nothing Selected>*",values:{0:{text:"Tick me",selected:false}}},isValid:true,
 # ignore datetime -  timeUpdated:
}}){clientMutationId}}
########### MUTATION END ###########
```
It's only affecting "prettier", so can still work, and seems to import okay.
