### ISSUE TITLE
Add proper reviewerAssignmentJoin entries to match the existing applications on db - to make the functionality of action work

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#314]

**Comment by CarlosNZ** [comment]
Suggestion: manually run the Action to generate them, then save a snapshot. Then just pull out the relevant mutations from the snapshot and paste them into the appropriate `insertData` script.

**Comment by CarlosNZ** [comment]
Actually, even that suggestion is going to be a bit overly tedious.

Another suggestion. How about I just provide a little bit of SQL (or GraphQL) to just set the Triggers on the handful of applications and reviews that exist, which will cause all these records to be (re-)generated.

And then export the database as a snapshot.

**Comment by CarlosNZ** [comment]
Nope that doesn't work. I've added suggestions to the "snapshots" issue (#312). If we implement that, then this will be much more straightforward.
