### ISSUE TITLE
Create new 3 policies with and only add the view permissions specific enforced (on application table)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#344]
## Policies

- **nonRegisteredApply**:  view: match by sessionID and userId = nonregistered (ideally, set `nonRegistered` user to id = 1 in database)
- **applyByUser**: view: match by userId??
- **applyByOrg**: view: match by orgId

Do we need one that matches by userId AND orgId, or are these two enough?

**Comment by CarlosNZ** [comment]
I think this is done, right?
