### ISSUE TITLE
Modify Entity Action

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#348]
Currently we have a "Create User" and a "Create Org" action. We also need an Action to "Update User" and "Update Org", as well as being able to (in future) create and/or update entities in any arbitrary table (e.g. Product).

Proposed solution is to combine all of these into one Action -- **Modify Entity**. Input parameters would be exactly as per current Create User/Org Actions, except would require an additional "table" parameter to specify what to update (e.g. user, organisation). It would also accept an "id" parameter, in which case the intention is to update an *existing* record. If no ID is supplied a new record will be created using the input parameters.

(It would be good to be able to not require an ID and do an UPDATE on any conflict, but this doesn't seem that easy since the ON CONFLICT command requires a specified constraint, and we can't ensure that our action would know in advance the unique fields of any particular table)

**Comment by andreievg** [comment]
I would call it 'record' rather than entity. To me entity sounds too ambiguous

**Comment by CarlosNZ** [comment]
> I would call it 'record' rather than entity. To me entity sounds too ambiguous

Sure.
