### ISSUE TITLE
Change status of reviews to "changes_requested" & consolidation to "pending" after a related review is submitted

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#363]

**Comment by andreievg** [comment]
This is based on a diagram: https://app.diagrams.net/#G1VIyFc7NjAEShXOQxgJoOvKgKrxbtsY0q

when consolidator submits a change request to change status of related reviews to changes_requested
when reviewer submits a review and consolidation is in anything other then pending, change to pending (I think this is already implemented)

**Comment by nmadruga** [comment]
> This is based on a diagram: https://app.diagrams.net/#G1VIyFc7NjAEShXOQxgJoOvKgKrxbtsY0q
> 
> when consolidator submits a change request to change status of related reviews to changes_requested
> when reviewer submits a review and consolidation is in anything other then pending, change to pending (I think this is already implemented)

Nice! Thanks for this summary and diagram @andreievg! Very helpful : ) I'm starting this issue now
