### ISSUE TITLE
New template -- Apply for licence (for Company)

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#377]
As per discussion with Craig 28/05/2021

Summarised in a diagram ("Laos Company Licenses.drawio" in LaoPDR folder), with references to details in Powerpoint

**Comment by andreievg** [comment]
Would be great to summarise what elements needs to be present in apply for licences form.

Also can creating a company be applying for licence ? (was wondering what the difference is between the two)

**Comment by CarlosNZ** [comment]
> Would be great to summarise what elements needs to be present in apply for licences form.

It's in the Powerpoint slides (plus Craig summarised it in a diagram, will find that tomorrow)

> Also can creating a company be applying for licence ? (was wondering what the difference is between the two)

One company can acquire multiple different licence types (Medicine, Natural Product, etc), so you wouldn't want to create a new company for each application. (FYI, "licence" in this context means certification and permission to submit a certain product type)

**Comment by andreievg** [comment]
> One company can acquire multiple different licence types (Medicine, Natural Product, etc), so you wouldn't want to create a new company for each application. (FYI, "licence" in this context means certification and permission to submit a certain product type)

Could a company apply for extra licences ? But the first licence application is when it's created ?

Otherwise anyone can create a company in the system. Valerio would see this as the 'break' point of our design.

**Comment by CarlosNZ** [comment]
> Could a company apply for extra licences ? But the first licence application is when it's created ?

Yes, it could. You'd have to use some logic to select an existing company and pre-fill the company info fields with existing defaults. And then the back-end Action would have to figure out whether to create a new company record or not on Approval. And then you'd need to figure out how to specify that the reviewer should be reviewing company info for new company applications, and only the import application info for existing orgs. There's several different ways to handle this that I can think of, but none of them are without some degree of configuration complexity.

Or you could just have two different Apply for Licence templates -- one for new companies, and one for existing companies. 

> Otherwise anyone can create a company in the system, I think that would cause issues

Yes, that's true. I guess it would be up to each country which approach they wanted to take. And hence we need to discuss the best way to make it possible, using Laos' specific case for starters.

**Comment by nmadruga** [comment]
I had a look on the slides now, to me this seems it should be same thing as the "Company registration", which would give this company a new license number with an expiry date. There is only differences in some fields depending if the company type is:
- MMC  MMM  MDC  MDM  WSL  RIT: MODERN MEDICINES OR MEDICAL DEVICES (Slides 32-35)
- THC  THM: TRADITIONAL MEDICINES OR HEALTH SUPPLEMENT (Slides 36-39)
- RTHC  RTHM: TRADITIONAL MEDICINES OR HEALTH SUPPLEMENT (Slides 40-43)

And then there is another template type (described in slides 44-47) to renew the company license (just for MODERN MEDICINES OR MEDICAL DEVICES - Not sure if the others can't be renewed).

**Comment by nmadruga** [comment]
> > Could a company apply for extra licences ? But the first licence application is when it's created ?
> 
> Yes, it could. You'd have to use some logic to select an existing company and pre-fill the company info fields with existing defaults. 
I agree that this should be part of the company registration. And we also need to deal with the expiry of this license (or licenses in case more than one is applicable for the same company) and just do this as part of the process for authorising a company to be included in the system. 

> And then the back-end Action would have to figure out whether to create a new company record or not on Approval. 
> And then you'd need to figure out how to specify that the reviewer should be reviewing company info for new company applications, and only the import application info for existing orgs. There's several different ways to handle this that I can think of, but none of them are without some degree of configuration complexity.

Why not having 2 different applications, one for "updating" or "renew" a license (that also allow you to apply for another one) and one just for company registration with the option to select between the type of the company:
 1. MMC MMM MDC MDM WSL RIT: MODERN MEDICINES OR MEDICAL DEVICES
 2. THC THM: TRADITIONAL MEDICINES OR HEALTH SUPPLEMENT
 3. RTHC RTHM: TRADITIONAL MEDICINES OR HEALTH SUPPLEMENT

Then would display the other fields and required documents based on that. Or another option, just requires more templates created is having one for each different typo of import type, but one for "creating" and another for "updating". I like this solution better because the config would be less complicated (although very repetitive).
