### ISSUE TITLE
Create new template to "Create a company" using the Laos workflow

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#388]
This questions should be included as part of the create company for now and have partial question included in the user table and another part included int he company table:

-applicant name
- date if birth
- national ID
- date of issue (for national ID)
- Current adreess
- Education (List builder)
  - university
Q: Is the user the applicant? - Email sent to Valerio

- Professional experience (List builder):
  - Area (Radiochoice)
    - government
    - private sector
  - Name of institution (if government)
  - Name of company (if private section)
  - Period of role
  - Telephone
  - email

**Comment by CarlosNZ** [comment]
@nmadruga -- here's a list of the docs required for MMC, etc. I've bolded the ones I thought I would include in company registration, so you shouldn't need them in licensing application. However, I'm not exactly sure if this is correct, so feel free to point change it, or we could discuss it sometime. We'll probably need to just ask Valerio .

- LMMD01 – Letter of request (physical submission also required)
- **LMMD02 – CV of applicant with recent (max 1 year) photo**
- LMMD03 – medical certificate (max 3 months)
- **LMMD04 – Certificate of current residence with photo (max 3 months)**
- LMMD05 – Recent (max 1 year) photo (to be used when printing licence)
- LMMD06 – Certificate of education level
- LMMD07 – Criminal record “number 3”
- **LMMD08 – Letter from previous employers documenting at least 3 years professional experience (for private sector must be certified by provincial or capital level)** 
- **LMMD09 – Documentation showing resignation from previous employment (for private sector must be certified by provincial or capital level)**
- **LMMD10 – Map of location of company**
- LMMD11 - Layout of facilities
- LMMD12 – Letter from mother-company authorizing establishment of branch
- LMMD13 – Proof of ownership of facilities or contract of rent
- **LMMD14 – Copy of business licence issued by Ministry of Commerce**
- LMMD15 - Site inspection report by F&D unit 
**- LMMD16 – Company/manufacturer profile (including site master file and GMP certification where applicable) describing origin of products, staff and qualifications, facilities and equipment, business experience, business development plan**
