### ISSUE TITLE
Verification endpoint - link to an action

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#416]
### Back-end
- new table in DB -- "verification", with fields "unique_id", "is_verified", "timestamp", "expiry" and "trigger"
- new Trigger "ON_VERIFICATION"
- new endpoint `/verify` which takes uniqueId as query parameter and sets "is_verified" to `true` and sets trigger to "ON_VERIFICATION", returns `{verified: true}` to caller
- if current time > "expiry", reject verification 
- new Action "createVerification", which generates a uniqueId, stores it in the verification table, set to `is_verified = false` and outputs the uid to Output object (for use by subsequent Actions)

### Front-end
- new route `/verify`, where our verification links direct to. Passes the query parameter (?id=xxxx) to the `/verify` endpoint above
  - UI if not verified yet -- shows and confirms verification, link back to Dashboard (similar to Submission page)
  - If already verified, show "Already used this link" 

### Templates
- update templates (start with UserRegistration) to use this implementation:
  - ON_SUBMIT -- create verification action, and send notification with verification link in it
  - ON_VERIFICATION: create user

### Questions
- should "expiry" be a timestamp, or a duration (e.g. 6 hours). Probably best for "createVerification" action to take a duration as input, but set "expiry" timestamp at creation time, right? And what unit to accept? (I'm thinking "hours")

**Comment by andreievg** [comment]
@CarlosNZ, looks good !

Can we also store verification message ? (this can be returned together with  { verified: true } and displayed).

Is ON_VERIFICATION on application ?

How do we pass data from verification to ON_VERIFICATION trigger (in case there are multiple verification for an application)

We would need another trigger ON_VERIFICATION_EXPIRED ? (as part of scheduling work).

I like the action idea (originally though that an action would be defined inside an action), just need a link between the action and verification. For prototype implementation can leave this out, but good to think that through (I dont' think it's that easy as we don't really know what verification set ON_VERIFICATION trigger).

> (I'm thinking "hours") 

sounds good to me, do we want to create evaluation wrapper for luxon ? (simple one and extend over time), could have:
```JS
{ 
  operator: 'relateiveDate',
  unit: DurationObjectUnits, // from luxon
  value: number
}
```

Last thing to consider, is authentication (this is for future use cases), where user_id can be stored on verification table and JWT checked for that user_id

**Comment by CarlosNZ** [comment]
> Can we also store verification message ? (this can be returned together with { verified: true } and displayed).

Sure, good idea!

> 
> Is ON_VERIFICATION on application ?

Was thinking it would be on verification table -- gets set along with setting "is_verified = true"

> 
> How do we pass data from verification to ON_VERIFICATION trigger (in case there are multiple verification for an application)

Hmm, good question. when the ON_VERIFICATION trigger fires, the processing knows the table and record id  of the verification code, so any additional data could be looked up in the verification table. We'd just need to add some extra fields (or how about just a "parameters" JSON field?) to bundle and pass on any additional data.

For distinguishing between multiple verification trigger on the same template/application, the "createVerification" action would just need to specify a unique code for each, then when the Actions run, there is a condition expression to check the "code" matches the verification code.

So, to summarise, the verification table would contain:
- id
- unique_id
- code (specified by template, used to distinguish between different ON_VERIFICATION events for the same template)
- created_time (NOW())
- expiry_time (created_time plus hours, or null)
- message (evaluator query, interpreted as Markdown by front-end -- like Submission message)
- data (JSON -- custom parameters, if required)
- is_verified (true/false)
- trigger

> We would need another trigger ON_VERIFICATION_EXPIRED ? (as part of scheduling work).

Yes, wasn't actually thinking we would trigger events on expiry, more just for rejecting a verification attempt if it's too late. For actual expiry "events" (e.g. license runs out), would be handled with "Scheduled Actions". I can't think of a use case for an event to occur on verification expiration -- most expiries would be handled by Scheduled Actions, but  maybe there is?

> I like the action idea (originally though that an action would be defined inside an action), just need a link between the action and verification. For prototype implementation can leave this out, but good to think that through (I dont' think it's that easy as we don't really know what verification set ON_VERIFICATION trigger).

Ah, see above -- I think the optional "code" field would do this.

> > (I'm thinking "hours")
> 
> sounds good to me, do we want to create evaluation wrapper for luxon ? (simple one and extend over time), could have:
> 
Not sure that's neccessary at this point, as Luxon expressions are super easy to write -- a call to an evaluation wrapper would be almost as verbose as the Luxon expression itself, I think.

> Last thing to consider, is authentication (this is for future use cases), where user_id can be stored on verification table and JWT checked for that user_id

Yes, could do -- although probably leave this out for now. Usually with verification emails, you don't need to be logged in to verify (the unique id acts as the authentication token effectively)
