### ISSUE TITLE
New action-plugin to generate the application name on Application on Start and Submission (to update with specific fields)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#427]

**Comment by CarlosNZ** [comment]
Are we happy if this action takes in a "formatString" parameter that follows the same format as I've done for the listBuilder and search plugins?

Eg. `formatString: "${template.name} - ${responses.productName}"`

where the fields come from 'applicationData', so the application would get a name like "Drug Registration - Paracetamol" in this case.


Also -- as part of this issue, I think it would be a good idea to extend "applicationData" to have more info (e.g. template.name), do you agree?
