### ISSUE TITLE
Generate assignmentJoins for current user on all available applications after user is associated to permission to review

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#429]
Run async the existing action `generateReviewAssignment` for each application and the current stage/level to generate the reviewAssignmentJoins

#### Create NEW "Parent" action "refreshReviewAssignments":

- takes "userId" as parameter
- searches for:
  1. all applications with review assignments for this user
  2. all applications that the user COULD have assignments for (i.e. based on permissions)
- from that, build a list of application Ids
- iterates over the application Ids, calling existing "generateReviewAssignments" action for each one sequentially
- The above iteration should be run sequentially, but this parent action can (maybe optionally) be run Async so it doesn't hold up the submission trigger and cause a time-out

##### Changes to EXISTING "generateReviewAssignments" Action:

- if only an "application Id" is provided (i.e. not a reviewId), then the first thing the action should do is lookup the highest review stage/level for this application from the review_assignments table. 
  - If there are none, it's assumed to be an application submission and the action proceeds the same as it does now
  - if there *are* some, then it's assumed that this is a "regeneration" and it should run for the **current** (i.e. highest) review stage/level and not the **next** one which would be the case when supplied with a reviewId (as in a review submission)
- Further down, the action needs to compare the newly calculated reviewAssigments with the existing ones, and DELETE any from the database that are no longer correct

### Considerations

- Do we need to have a flag somewhere ensuring that multiple instances of this Action can't run simultaneously? Could it cause problems if it did? If so, how do we do this? (Perhaps it checks for the entries in "action_queue" with "actionCode = generateAllReviewAssignments" AND status = PENDING, then doesn't continue until there are none left, or else it times out after one minute)

**Comment by CarlosNZ** [comment]
Updated original post with some requirements / suggestions for consideration

**Comment by nmadruga** [comment]
Ok here is my alternative version - as discussed in the meeting today with Carl, Andrei and I

### New action to run after grant/revoke user's permissions

#### Input parameters
userId / username - or array of users?
grantedPermissionNames - array strings
revokedPermissionNames - array strings

Should use the resulting array from grantPermissions and revokePermissions on the next action that would run. Let's call it **updateUserReviewAssignments** for now. Here is some example arrays returned by previous actions:
##### grantedPermissions:
```
Granting permissions:
{
  username: 'maria',
  orgName: undefined,
  orgId: '1',
  permissionNames: [ 'reviewJoinOrg', 'reviewAssessmentLevel2', 'reviewProdAssessment' ]
}
```
##### revokedPermissions:
```
Revoked permissions:
{
  username: 'maria',
  orgName: undefined,
  orgId: '1',
  permissions: [
    {
      permissionJoinId: 14,
      permissionNameId: 9,
      permissionName: 'reviewScreening'
    },
    {
      permissionJoinId: 46,
      permissionNameId: 12,
      permissionName: 'reviewAssessmentLevel2'
    }
  ]
}
```

### Logic in action:

- For each grantedPermissionName, get applications that are COMPLETED, in the same stage in templatePermission uses this permissionName (`permissions_all` have this info) and have at least one entry in `template_stage_review_level`. 
- **Note**: Only application with reviews have only been submitted (we always would create reviewAssignments for the same stage/level - no need to create for next level as it’s done in generateReviewAssignments when isReview)
- **Note 2**: We need to get which is the current review stage/level available. The application has the stageNumber, but not the levelNumber, and we don’t need to create assignments for previous level of reviews (I think).
   - For each application get last review and then stageNumber & Level, something similar to what is done in - although we don’t have the reviewId.
   ```
    const { stageNumber: submittedReviewStage, levelNumber: submittedReviewLevel } = await DBConnect.getReviewStageAndLevel(reviewId)
   ```
- With all information about review level on each application (of each template type and stage that matched the permissionName) we check if there is already an reviewAssignment created for **this user** - and finish creating one.
- Similar thing not for revokedPermissionNames, but last stage should check if there is one ReviewAssignment - which isn’t linked to a Review or if Unassigned (Status = DISCONTINUED). Finish removing if existing.

**Comment by CarlosNZ** [comment]
> * For each grantedPermissionName, get applications that are COMPLETED, in the same stage in templatePermission uses this permissionName (`permissions_all` have this info) and have at least one entry in `template_stage_review_level`.

Don't you mean *NOT* COMPLETED?

> Note 2: We need to get which is the current review stage/level available. The application has the stageNumber, but not the levelNumber, and we don’t need to create assignments for previous level of reviews (I think). 

Would it be safer/easier to just do ALL the levels for the application/stage? It's slightly less efficient, but it's still going to be a lot faster than my original suggestion (since we're doing it for a much smaller list of applications), and finding the exact level (without the current review_id) might require some messy logic.

> Similar thing not for revokedPermissionNames, but last stage should check if there is one ReviewAssignment - which isn’t linked to a Review or if Unassigned (Status = DISCONTINUED). Finish removing if existing.

Also need to account for the status. If it's "ASSIGNED", we need to adjust the others accordingly. This is why I think we still need to run the "generateReviewAssignments" Action, as we don't just need to update the ones for that user, we also need to update all the ones for the other reviewers with review_assignments connected to that application.

Also -- need to generate the review_assignment_assigner_joins too.

I'm thinking that perhaps a hybrid approach might work -- use your logic to just find the applications associated with the user in question (so we get a smaller list), but then still run "generateReviewAssignements" for each of those?

Maybe we can have a chat about it tomorrow morn? (I'll keep thinking about it overnight)

**Comment by nmadruga** [comment]
Thanks for other inputs, Carl. I'll update the one about getting application NOT COMPLETED and chat about other things your pointed out in a meeting with you today. Let's aim for after lunch? 2pm. 

> I'm thinking that perhaps a hybrid approach might work -- use your logic to just find the applications associated with the user in question (so we get a smaller list), but then still run "generateReviewAssignements" for each of those?


There is a problem with using `generateReviewAssignments`  which is , well the logic is aiimed to create reviews for **nextLevel**, so don't think it would work as expected... Also the reason to find which is the current level, is because we don't want to create next level reviews before it's time, because then one reviewer would be able to start a review before it's time...

**Comment by CarlosNZ** [comment]
> There is a problem with using `generateReviewAssignments` which is , well the logic is aiimed to create reviews for **nextLevel**, so don't think it would work as expected... Also the reason to find which is the current level, is because we don't want to create next level reviews before it's time, because then one reviewer would be able to start a review before it's time...

Yeah good point. It doesn't matter if we re-create review assignments for earlier levels, but yeah, we can't create future ones yet.

I still think running the existing `generateReviewAssignments` action is the best bet once we've established each application and review level, since the logic from there on will be exactly the same. Then it's just generating the list of applications and review levels that needs to be figured out.

But yeah, chat at 2 sounds fine. I can do earlier if you want though.
