### ISSUE TITLE
Update incrementStage and generateReviewAssignments to only run if application outcome is still PENDING - so it doesn't run after the outcome changes

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#461]

**Comment by CarlosNZ** [comment]
Just wondering -- if the Outcome has changed from "PENDING", why would applications be triggered?

Do you mean on the final approval submit? If so, it doesn't matter if they run, as they've both been set to not do anything if there's no further levels/stages. I'm not 100% sure for generateReviewAssignments, but I'm sure that you can't increment a stage past its final stage, so no need to change anything there.

**Comment by nmadruga** [comment]
Hi @CarlosNZ, this is required now that we have changed to run a core_action for a chageOutcome to happen for any application when review is last level and stage is last stage. This will always change the application outcome based on the review decision.

Now, for some specific applications we want to set on the template an action to change outcome before the last stage, for example on Drug Registration, when in the Screening the review has set NON_CONFORM it should change the outcome as well. And then after the incrementStage action should run and not change the stag, since this application has outcome not PENDING.

**Comment by CarlosNZ** [comment]
Okay, I see. So it's for when an application is complete (via rejection) on an early stage and we want to make sure it never goes to another stage.

Wondering what the best place to put this, as I'm not sure we want to put more logic into the actions that is for specific cases. We can probably do it by defining the condition on the template_action -- Outcome is "PENDING". I think that would _probably_  be clearer, but maybe it'll end up being overly verbose in the template. Probably if it's in core_actions (and thus not needing to be copied into every template), then it makes sense to put it as a condition expression.

**Comment by nmadruga** [comment]
> Wondering what the best place to put this, as I'm not sure we want to put more logic into the actions that is for specific cases.

We considered both option - sending as configuration or adding as part of the action. Remember that, if in a country they don't want this restriction on the core action, then the core action plugin can be changed to something more specific. But Andrei and I agreed that it's unlikely this would ever get changed so that's why is in the action.

**Comment by nmadruga** [comment]
> but maybe it'll end up being overly verbose in the template.
