### ISSUE TITLE
Scheduled Actions -- summary of work needed

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#470]
### 1. Schema changes

- New table "action_schedule" -- fields: `id` (primary_key), `table_name`, `entity_id`, ~~`template_action_code`~~ `event_code`, `time_scheduled`, ~~`condition`~~, `application_id`, `template_id`, `is_active`,`trigger`
  - basically a link between an entity (e.g. application, review, outcome entity) and an scheduled event, and the template_action associated with it. I initially thought that each table that needs one could have its own "expiry"/"scheduled_time" field, but since any arbitrary table (for new outcomes, etc.) needs to be watched, it'd be easier if all scheduled events are in the same place, otherwise we'd have to keep a separate, updating list of where to check.
- New trigger "ON_SCHEDULE", and add the standard trigger logic to action_schedule table 
- `code` field added to `template_action` table -- not compulsory, but must be unique per template (used for unambiguously identifying which action should run when there might be multiple actions of the same (action_code) type per trigger)
- trigger functions also pass "template_action_code" through as part of "trigger_payload"
- also add "template_action_code" to "verification" table -- not part of this issue, but it makes sense for verification to have the same logic available to link "events" with template_actions

### 2. triggersAndActions.ts -- update to handle "code" field

- "processTriggers" fetches the new "code" field of the template actions it loads on trigger, and matches them with any "template_action_code" in the trigger payload. If "template_action_code" is specified, then actions must match in "code" field, but if not, then all actions for the trigger are processed as normal
- after action executed, when resetting the trigger (like normal), we also set `is_active = false` if it was a scheduled_action

### 3. New Action -- Set action_schedule

- Input parameters:
   -  table
   -  id
   -  duration -- the time to add to the current time for expiration. Probably a Luxon "duration" object, but should also accept a simplified "number" value (which would be interpreted as weeks)
   - code -- not compulsory, but corresponds to the unique code field for the action that should be triggered by this scheduled event
   - ~~condition -- (default: true) an evaluator expression that is evaluated at the scheduled time to determine if the scheduled event should run -- basically the same as "condition" field on template_action, but it's easier (in some cases) to associate the condition with the scheduled event itself rather than the action that runs as a result of it (although it could be argued that this is a trivial distinction and we should just stick with the "condition" field on the triggered action -- open to alternative ideas of how to allow "cancelling" of scheduled events?)~~ I actually think just having the standard "condition" field on the executing Action is more straightforward.

The Action would then just convert the duration into an actual date/time (as per createVerification action), and then enter the scheduled action into the "action_schedule" table. ~~We need to make sure we _update_ any existing scheduled events, so for renewals we can extend an existing expiry time rather than create a new record for the same entity~~ (prob not necessary with the extra "condition" check)
The "template_id" and "application_id" fields can be set using applicationData info.

### 4. New Action -- revoke permission

As discussed, and maybe make modifications to "grantPermissions" to check existing rather than create new entries

### 5. Template Actions

- Add "Set action_schedule" actions to templates -- "template_action_code" for these should correspond to the "code" of the "ON_SCHEDULE" actions below. And they need to have conditions that reflect when they should and shouldn't run (e.g don't send notification if application is already SUBMITTED)
- Add template actions that are triggered by "ON_SCHEDULE". The actions would trigger things like "revokePermissions", "sendNotification", etc.

### 6. Scheduler module

- first step is remove existing "Scheduled Actions" functionality (and remove "ON_SCHEDULED_ACTION" trigger). We'd still keep the "node-scheduler" package, but it would now only run a single job at a predetermined interval (default: daily at midnight?, and on server start to catch any that have been missed while server not running)
- When it runs, it checks the "time_scheduled" table, and any dates that are earlier than the current time and `is_active = true`, those records get their "trigger" field set to "ON_SCHEDULE"
- update trigger/action processing to make sure the "table" and "record_id" in the trigger payload are set to the _originating_ (from the entity) table rather than the "expiry" table (this might not be necessary if using the unique "template_action_code" to link scheduled events with template_actions)
- ~~after Action is dispatched, set the "is_active" field on action_schedule to `false` (it'd be good if this was only set after we know the action ran _successfully_, but I'm not sure that this is straightforward)~~ This is done in triggersAndActions (above)

---
Considering Epics:
- Certificate expiry
- Template expiry configuration (applicant and review/stage allowed time)
- Application expiry

**Comment by CarlosNZ** [comment]
### Alternative Implementation

(Sorry that this is so brief/vague, just that I'm not as clear on how it could work fully -- any one who is in favour of this approach might want to update it with more detail)

In summary, we would have a new Action "Set Scheduled Action" which would enter the appropriate data directly into the "action_queue" table, but with status "SCHEDULED" instead of "IN_PROCESS"

The "Scheduler" module would then, when it runs (as per above), check the "time_scheduled" field (this already exists) of "SCHEDULED" actions in the action_queue, and set the "status" to "IN_PROCESS" which would cause the actions to fire off as per normal

#### Advantages of this approach

- easier to discriminate between different expirations for the same template (slightly)
- ??

#### Problems/questions with this approach

- Syntax more complex, since you'd have to describe an entire action's parameters inside an outer action (it's nested listBuilder all over again)
- How do we handle it when we don't want the action to run (i.e. licence has been renewed, so doesn't now expire). We can change the "time_scheduled", I guess, but it might be harder to identify the exact action_queue entity to be updated (we don't really have a way to uniquely identify action_queue items) (this is the biggest problem with this approach, IMHO)
- It would be hard to get a "sequence" of actions to run this way, since they'd no longer be processed as part of a single trigger event. Maybe it would be better if the "Set Scheduled Action" just entered the "trigger_queue" event with a schedule, and then that trigger would launch its (sequence of) actions as per normal, just delayed?

**Comment by andreievg** [comment]
Thanks for the summaries, can we get a diagram or description of pseudo workflow of what actually needs to happen for expiry management, would be good to have this before evaluating the solutions. i.e.

* when application is submitted and outcomes is generated 
* expiry is set to an outcome of (approval date + configured duration)
* when expiry is reached an outcomes becomes expired, and user is restricted from submitting/creating certain applications (would revoking permission mean user wont' be able to see a list of applications anymore ?)
* when renewal is processed expiry is updated on outcomes to -> renewal date or expiry date (latest) + configured duration.
* (optional) notification is sent at expiry date - configured duration

**Comment by CarlosNZ** [comment]
> when expiry is reached an outcomes becomes expired, and user is restricted from submitting/creating certain applications (would revoking permission mean user wont' be able to see a list of applications anymore ?)

This is a good point that we haven't really considered. I think this could be solved when we "revoke" permissions, we just set the entry to "disabled" (as we discussed in meeting), and not delete it. Then we can discriminate between three states:

1. no permission: can't see applications, nor create new ones of that type
2. has permission, not "disabled": can see applications and create new ones
3. has permission, but "disabled" (revoked): can see existing applications, but not create new ones

Not sure which logic would need to change to accommodate this, but at least we can easily discriminate between the different situations.

**Comment by nmadruga** [comment]
> New trigger "ON_EXPIRY", and add the standard trigger logic to expiry table

I suggest ON_EXPIRY_END

**Comment by nmadruga** [comment]
> The "template_id" and "application_id" fields can be set using applicationData info.

I guess that the need for `template_id` if this is something not linked to an application? Otherwise the template_id can be found inside the linked application in a nested Graphql query

**Comment by CarlosNZ** [comment]
> Thanks for the summaries, can we get a diagram or description of pseudo workflow of what actually needs to happen for expiry management, would be good to have this before evaluating the solutions. i.e.

Good idea to create case examples, helps clarify the requirements. I've made a doc with some typical scenarios:

https://docs.google.com/document/d/125E32k7-_fWMphLdIwizntLeyOdP5ej15z69SXaBHRU/edit#

This just describes WHAT has to happen and when, not HOW it should be implemented.

**Summary of requirements**:

- On triggers, need to be able to schedule a sequence of Actions for some time in the future
- Need to be able to cancel (i.e. prevent from running) those scheduled actions on certain conditions/triggers
- Need to be able to have several different scheduled events and easily tell which action to run at which time/event
- Regularly check for expired (past scheduled) events and execute the actions (in sequence)

In light of this, I'll re-think my above suggestions. I'm leaning towards some kind of combination of the two options, will think it through some more.

**Comment by CarlosNZ** [comment]
> I suggest ON_EXPIRY_END

Or just ON_EXPIRATION ?

**Comment by nmadruga** [comment]
I agree that a diagram will be very helpful. Starting to read the doc with typical scenarios and don't really see where the actual action to run "send notification" and "change outcome" of application are.  From what I read in the description of this issue it seems that the current idea it that we define 2 actions `sendNotification` and `changeOutcome` for trigger ON_EXPIRATION? I can't really see this clearly yet. I thought we would need one action with parameters to check if:
- Notification needs to be send (and what message)
- outcome needs to be changed

**Comment by CarlosNZ** [comment]
> don't really see where the actual action to run "send notification" and "change outcome" of application are

They would just be regular actions, same as normal ones, but with the "ON_EXPIRATION" trigger, and probably a condition.

**Comment by nmadruga** [comment]
Thanks for briefing these new features. I think I get most of the idea, and agree with this approach, the alternative seems complicated also having this queue_actions for long time in the queue would be annoying. And probably error prone in case of a server re-start.

I guess we will continue to define how we setup template expires - with deeper thought on reviews - because we might need to differentiate review expiry per stage/level - oh the same could be for applications too, right?
And consider in the configuration that reviews expiry that can be just warning and not actually revoking any permissions.

**Comment by nmadruga** [comment]
> They would just be regular actions, same as normal ones, but with the "ON_EXPIRATION" trigger, and probably a condition.

I wonder if wouldn't be good to combine calling each (or both) inside a new action "updateOnExpiry" or something similar - just because we might have too many cases to add on the core_actions. And it would be clearer using this action?

**Comment by CarlosNZ** [comment]
> I wonder if wouldn't be good to combine calling each (or both) inside a new action "updateOnExpiry" or something similar - just because we might have too many cases to add on the core_actions. And it would be clearer using this action?

I think the important thing is there's nothing "special" about these actions, they're just like every other action, they run in sequence (or async) on a specific trigger. So I'd be reluctant to treat them any differently.

**Comment by CarlosNZ** [comment]
After running through the case examples and thinking about it some more, the main thing I'm not happy with is how we cancel scheduled actions/expirations. It's far too messy to have a whole other "Cancel Schedule" action, with all the conditions and situations that would be required.

My current thinking is to have one more field on the "expiry" table: `condition` -- which is an evaluator expression. And when the scheduler runs, it evaluates the condition expression and only sets the trigger "ON_EXPIRATION" if `true`. So it would work basically the same as the "condition" field on template actions, but it'd be evaluated at the time it is scheduled. 

So, for example, you'd schedule an event for 2 weeks which would, if triggered, run a "Send Notification" action. But the condition would be "`status != "SUBMITTED`", so if the applicant has already submitted they don't get a notification.

Also -- thinking about the way we link expiry/schedule events back to template actions and it can get quite messy if there are a lot of different ones. Perhaps it's time to implement Andrei's suggestion of an "instance code" for each template action? This would also help with:
 - verification linking (same issue)
 - discriminating between different "Outcome" objects of the same type

**Comment by CarlosNZ** [comment]
Okay, I've updated the [original post](https://github.com/openmsupply/application-manager-server/issues/470#issue-953425206) based on this discussion and some further thought. I realise that some of the explanation is somewhat confusing and I've introduced some terms/concepts that I haven't fully explained, but I'm happy to clarify it IRL in the morning.

The only part I'm not fully happy with is the "cancelling" mechanism (by adding "condition"). It'd be good to have a mechanism to properly "cancel" events by marking them as cancelled in the action_schedule (which means they'd never even be considered again, so we don't have to worry about accidentally "uncancelling" them due to unexpected application/condition states), but I haven't yet thought of a way to do this elegantly (having a bunch of additional "cancel scheduled action" actions on various triggers is a no-go as it adds way too much overhead and convoluted logic to templates) -- so any other suggestions welcome.

**Comment by CarlosNZ** [comment]
Thinking about it a bit more, I think we have two choices for "cancelling" actions in terms of actual behaviour (not necessarily implementation), and I'm not sure which one is more useful for our use cases:

1. As described above, scheduled actions get their "condition" evaluated at the scheduled time, and only run if `true`. 
2. Scheduled events get "cancelled" as soon as their condition becomes `true` and never get looked at again.

As far as implementation goes, here's how we might do it:

1. As described above -- just evaluate the condition at the scheduled time
2. On every trigger, we check the conditions for all scheduled events associated with the application, and any that are `false` get set to "disabled" and can never run

I *think* option 1 is fine, and probably safer overall. However, it'd be good if anyone could think of use cases/scenarios where the incorrect behaviour could occur (i.e. sending out notifications that shouldn't be sent)

**Comment by CarlosNZ** [comment]
> However, it'd be good if anyone could think of use cases/scenarios where the incorrect behaviour could occur (i.e. sending out notifications that shouldn't be sent)

Here's one: if an applicant starts an application, we can schedule an expiry for say 3 weeks. The scheduled action (set outcome to "EXPIRED") will run on the condition that the application status = DRAFT.

They submit, a review looks at it, requests some changes. The applicant re-starts it, and now it's in DRAFT again. However, the original expiry shouldn't apply, they should have a new expiry that starts the 3-week (or whatever) countdown again. However, the original scheduled expiry will still fire in this case, as it meets the condition.

This is a problem.

Possible solutions:

1. A more complex condition (i.e. status = DRAFT and no reviews exist) -- not keen on this as the conditions could get stupidly complex.
2. Run the condition check for existing scheduled events after EVERY trigger and disable as soon as the condition is not met (suggested above). Problem with this is I can imagine scenarios where we inadvertently cancel scheduled actions if a condition is momentarily false.
3. (This is my preferred solution, I think) Use the Code. First of all, regarding codes -- they needn't be unique per template, they're essentially an "event code", because if you have a scheduled action that you want to trigger more than one action in a sequence, they'll need to have the same code. So, in this case, my suggestion is to have another scheduled action launched ON_APPLICATION_RESTART, that sets the same schedule with the same code. So then the "scheduleAction" action needs to _update_ existing schedules with the same code (and applicationId) rather than create a new one. So the "template_action_code" doesn't need to be unique per template, but it will be unique per scheduled event per application. 

Any other ideas?
