### ISSUE TITLE
Summarise changes to start using snapshots + template builder to keep our dev insertData and laos insertData as snapshots considering tests which would require assignment and reviews already created

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#474]
### Tests and initialising database
- Create 2 snapshots: one for `dev` another for `laos`
- Perhaps one without any templates - just schema loaded. What are the benefits?
- When loading the `dev` snapshot - reviews and reviewAssignments for ReviewTest would be created - so changes to this template would be a problem since fields/table might not match correctly anymore

### Storing: version control vs sharing folder
- Where do we store our snapshots?
- If keeping on a repository, we can use diff to compare changes. Would that be helpful?

### Exporting snapshots
- Change/add options on the script for snapshot to only export latest or just the **active** version of each template - so we remove all different versions created previously for the same template

### Create new templates
- Carl and I were trying to figure out the best strategy to duplicate same actions that are likely to be used in every template. We have core actions - and one possibility would be to just copy all core_actions to a new template (not duplication of template). But actions for notifications - which would be very repetitive between different templates -  shouldn't be core_actions (since the definition of this is required for the correct flow of the App). The idea was to have a simple **base template** that would be copied in case the Admin user would like to start a new template - from scratch. The base template would have the most basic setup, but considering all notifications and other specific actions to easy the creation of a new template

### Create new core_actions
- Ideally adding new core actions can be done from any template, so having a flag to say this is a core action and when saving the template a copy of this action would be sent to where other core_actions are kept (for now `core_mutations.js` file)
- Any template could import all new **core_actions** that aren't already in this template - to get all latests additions
- Not a good idea to overwrite/or manage diffs between existing core actions and current changes on specific template.  
- Having a **code** per action/template would be also helpful here so we can check what core_actions are missing by looking if all actions by codes from core_actions are included in the current template

**Comment by nmadruga** [comment]
My initial plan of issues to create and get the setup started:
1. Create clean snapshot without templates - should have only base template?
2. Work out how to change script to generate snapshot only with latest version of each template
3. Create & implement button to create new template (copying base template)
4. Start second snapshot only with Laos config using base template and copy other fields
5. Start third snapshot only with dev config. It should also have already all 6 existing applications/reviews created
6. Make sure tests are running well on dev snapshot
7. Publish 3 snapshots with only one version of each template
8. Write documentation on how to use new environment

**Comment by CarlosNZ** [comment]
Sounds good. 

>  1. Create clean snapshot without templates - should have only base template?

I don't know if we need this, since we're still going to need the SQL scripts to build the schema, as any changes we do to the schema will be done in the SQL scripts.

Also, along those lines, how do you think we should handle migration? Like, if we make a schema change and it makes the snapshots invalid (changed/removed field perhaps?) do we have a strategy to update the snapshot data?

> 3. Create & implement button to create new template (copying base template)

I thought we were just going to go with duplicating existing templates for now?

> Where do we store our snapshots?

Maybe we can keep most of them in a Google Drive folder, but we keep the "master" (the current "official) versions of templates / data files in repo?

One thing we would want to keep in the repo is a collection of "options" configs, for different kinds of exports (templates only, data only, etc.)

> Ideally adding new core actions can be done from any template, so having a flag to say this is a core action and when saving the template a copy of this action would be sent to where other core_actions are kept (for now core_mutations.js file)

As we discussed, I think "core" actions should only be the minimal set of actions to make the system work properly (i.e. increment stage on create, etc.) Other "common" but not essential actions can be part of "base templates" that we duplicate from.

>  Change/add options on the script for snapshot to only export latest or just the active version of each template - so we remove all different versions created previously for the same template

I think Andrei said we can already do this.

**Comment by nmadruga** [comment]
> > 1. Create & implement button to create new template (copying base template)
> 
> I thought we were just going to go with duplicating existing templates for now?

I think we can give 2 options: duplicate one template or start a new one (that would in the background copy the base template config - so you already have a very basic setup to start with)

**Comment by andreievg** [comment]
Some comments, I think overall it looks good (with private repo for country specific snapshots, and core 'dev' snapshot in existing repo, as long as we anonymise users). I want to have a more thorough think about this, hopefully will get some time today

> I think we can give 2 options: duplicate one template or start a new one (that would in the background copy the base template config - so you already have a very basic setup to start with)

I think duplication is enough tbh.

> Also, along those lines, how do you think we should handle migration? Like, if we make a schema change and it makes the snapshots invalid (changed/removed field perhaps?) do we have a strategy to update the snapshot data?

Ideally snapshot and template export would have DB version attached to it. This would allow for migration to be executed on them (not implemented), I've made an issue awhile ago regarding migration (https://github.com/openmsupply/application-manager-server/issues/414), which we should consider doing soonish.

I hope we would only be adding new fields/tables now (not renaming fields and tables)

> Create clean snapshot without templates - should have only base template?

> Publish 3 snapshots with only one version of each template

> Change/add options on the script for snapshot to only export latest or just the active version of each template - so we remove all different versions created previously for the same template

If there are no applications attached to a template, even if it's available, it can be turned into draft and edited, and then snapshot re-exported.

**Comment by CarlosNZ** [comment]
> I hope we would only be adding new fields/tables now (not renaming fields and tables)

What about Outcome tables?

**Comment by CarlosNZ** [comment]
Got the submodules working now! But when I run `yarn database_init` I get the following:

```
$ /Users/carl/Github/openmsupply-application-manager/application-manager-server/node_modules/.bin/ts-node ./database/snapshotCLI.ts use
3
undefined { isLastParameter: false, value: undefined }
using snapshot, name: current
using options from: /Users/carl/Github/openmsupply-application-manager/application-manager-server/database/_snapshots/current/options.json
{
  success: false,
  message: 'error while loading snapshot',
  error: "Error: ENOENT: no such file or directory, open '/Users/carl/Github/openmsupply-application-manager/application-manager-server/database/_snapshots/current/options.json'"
```

There's no "_current" folder in "_snapshots" -- should there be?

**Comment by nmadruga** [comment]
> Got the submodules working now! But when I run `yarn database_init` I get the following:
> 
> ```
> $ /Users/carl/Github/openmsupply-application-manager/application-manager-server/node_modules/.bin/ts-node ./database/snapshotCLI.ts use
> 3
> undefined { isLastParameter: false, value: undefined }
> using snapshot, name: current
> using options from: /Users/carl/Github/openmsupply-application-manager/application-manager-server/database/_snapshots/current/options.json
> {
>   success: false,
>   message: 'error while loading snapshot',
>   error: "Error: ENOENT: no such file or directory, open '/Users/carl/Github/openmsupply-application-manager/application-manager-server/database/_snapshots/current/options.json'"
> ```
> 
> There's no "_current" folder in "_snapshots" -- should there be?

Caused by something that was done to prevent another problem - it should be using the **basic_snapshot** when nothing gets passed to `yarn database_init` now... Will fix that in the PR. Thank you
