### ISSUE TITLE
Fix permissions to get previous-stage review for Final decision

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#483]
The query `getReviewInfo` is set to also get previous stage reviewAssignment, but with permission it doesn't return that and for that reason some preventions on ReviewHome needed to be done and the Review can't start - since it needs the last stage reviewAssignment to work

**Comment by andreievg** [comment]
Currently we don't allow review assignment that don't belong to the user to be accessible. 

The easiest solution is to have a new policy for Final Decision reviewer (and allow them to see all review assignments).

A more granular solution is to allow visibility of review_assignments for all stage of application that are below stage that is assigned to current user. But that might prove to be too difficult

**Comment by nmadruga** [comment]
> The easiest solution is to have a new policy for Final Decision reviewer (and allow them to see all review assignments).

Yes, that seems like an easy solution to me. Although it would mean that:
- Reviewer with Final Decision permission get to see all applications - which have a reviewAssignment created
- When permission is not correctly set the users wouldn't be able to make the Final Decision...

For the later, I think the option to allow visibility of previous level reviewAssignment (after your review assignment is created) would be the best option. But we might need to think this through first - and I would definitely need your help with this one.

**Comment by andreievg** [comment]
> > The easiest solution is to have a new policy for Final Decision reviewer (and allow them to see all review assignments).
> 
> Yes, that seems like an easy solution to me. Although it would mean that:
> 
> * Reviewer with Final Decision permission get to see all applications - which have a reviewAssignment created
> * When permission is not correctly set the users wouldn't be able to make the Final Decision...
> 
> For the later, I think the option to allow visibility of previous level reviewAssignment (after your review assignment is created) would be the best option. But we might need to think this through first - and I would definitely need your help with this one.

There is an intermediary solution I think, to allow all all review assignments to be visible, but see only applications for which you have review assignments with status (assigned, available for self assignment), how does that sound ? Basically the only difference between that one and current set up is to change:

https://github.com/openmsupply/application-manager-server/blob/a8bfc0f39e361b7da5c98f98611553efaff64f3c/database/insertData/_common/01_permission_policies.js#L161-L165

to 
```
review_assignment: {
          view: {
            template_id: 'jwtPermission_bigint_templateId',
          },
        },
```

**Comment by andreievg** [comment]
> For the later, I think the option to allow visibility of previous level reviewAssignment (after your review assignment is created) would be the best option. But we might need to think this through first - and I would definitely need your help with this one.

I actually don't know how to do this without changing/aggregating schema, since we would need to have a circular query

**Comment by nmadruga** [comment]
Add to PR #456 commit 036c618f86c5c651702d854ed3b8e0284ca51f1b
