### ISSUE TITLE
New external user can see all users / orgs

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/application-manager-server#533]
At the moment a new external user can see all users / orgs. 

![image](https://user-images.githubusercontent.com/19318937/130716925-4ed07972-0bd8-48be-a7dc-a02cf8f06bba.png)

Do we need to do something to restrict these?

**Comment by nmadruga** [comment]
I think this is fixed by PR @CarlosNZ

**Comment by CarlosNZ** [comment]
Yeah #600 -- thanks, I'll link it.
