### ISSUE TITLE
Replace {Regulatory Authority} with proper company name used in the system - it will have to be passed in applicationData for the action sendNotification

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#536]

**Comment by CarlosNZ** [comment]
How do you propose to identify the "regulatory authority" company in the system? We currently have the "is_system_org" field on "organisation", but doesn't have to be unique -- i.e. there could be multiple different "departments" stored as seperate orgs. So there's currently not really a concept of **the** regulatory authority specifically. Only thing I can think is to store the name as a config value in config.ts. Does that work?

**Comment by nmadruga** [comment]
That could be one way yes, I didn't know the answer. Was just considering would be nice to have a simple way to replace all when needed. Another option for future implementation would be to select one of the organisation with `is_system_org` froma dropdown to be signing emails
