### ISSUE TITLE
Not allow assignment/review/updates of applications with Template changed to Disabled

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#542]
See 2 applications below. The first one is related to a Disabled template and the second is related to Available.
Nice-to-have template number visible somewhere in the list of applications.
<img width="1138" alt="Screen Shot 2021-08-29 at 3 43 45 PM" src="https://user-images.githubusercontent.com/16461988/131237644-1fc9e3e6-d417-4674-afae-fd89c9957357.png">

Steps to recreate the problem:
 - Create application while the template is available
 - Duplicated template, disable original version, make a copy available
 - Create another application (now linked to a new template)
 - Show list of applications to the reviewer with permission to review
 - Both applications are showing to the reviewer, but only a second should be possible to assign/review/update

**Comment by nmadruga** [comment]
Seems related to this (on `28_review_assignment.sql`):
![Screen Shot 2021-08-30 at 11 38 47 AM](https://user-images.githubusercontent.com/16461988/131269061-6e44fd92-5c0f-4654-9fa5-5844b0315292.png)

**Comment by CarlosNZ** [comment]
You need to be able to complete a review process for templates that have been made disabled -- the only thing you can't do is start new applications.

For example, an applicant submits a new company registration. While waiting for review, the template gets changed and this version gets disabled. The application shouldn't be required to start a new application (and they'd have no way to know about it, anyway). The review process should continue as before, it's just any new applicants that will be starting with the new version.

So "Disabled" for a template just means "can't start new applications", everything else about it is exactly the same.

**Comment by nmadruga** [comment]
Ok. That's all good. I think we probably just need all these rules listed as part of the Template builder in some versioning area so we know about those rules. I'm starting toloose track of what is expected and what is missing some fix/improvement
