### ISSUE TITLE
Add languages json files to be fetched for selected language and replace values on the english.js in the client

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#561]
The file for the english will be a js file in the web-app and the keys, values replaced with what is in the json file when fetched.
Should be keeping this translations files inside the files folder (translation inned folder?)

**Comment by nmadruga** [comment]
We talked about having the name of the language and flag as part of the json, but to use that in the use that to seelcted the language in the UI would mean we need to fetch all - I would rather have the languages available (based on which files there are in this folder) added to a simple table that has the language name, path to the file and flag.

**Comment by CarlosNZ** [comment]
> We talked about having the name of the language and flag as part of the json, but to use that in the use that to seelcted the language in the UI would mean we need to fetch all - I would rather have the languages available (based on which files there are in this folder) added to a simple table that has the language name, path to the file and flag.

Yeah, makes sense. So maybe just another json file "languages.json", with an array of something like:

```
{
  languageName: "Portugese",
  description: "Portugese translation for Angola users"
  filename: "portugese_angola.json",
  flag: "🇦🇴"
}

```
