### ISSUE TITLE
Create action to send the email

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#57]
The email action plugin should already consider parameter to add PDF when the Emails are sent for some Application update. For the user registration:
- Email would be sent with link to finish registration of user.
- Email is send after registration is complete with welcome message (template_message).

**Comment by CarlosNZ** [comment]
Will probably use NodeMailer on the back-end: https://nodemailer.com

**Comment by CarlosNZ** [comment]
Question: should this Action also add a record to the "notification" table, or will we make "sendNotification" a separate action?

**Comment by nmadruga** [comment]
It seems a good idea to have both action, but also allow that the email action has the ability to write to the notifications table (when we start working with Notifications - probably not done in **June**) that would also be handy so when we use both, we don't have to repeat an action to do notification and another to do email sending. I just think that we should have a default behaviour on the "send email" to not be stored as Notifications and can be using an optional parameter - done later.
