### ISSUE TITLE
(User Registration) Remove comma and capitalise P in Please

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/application-manager-server#598]
![image](https://user-images.githubusercontent.com/19318937/135159812-e5449e31-fe39-446c-a883-9dc97365058b.png)

**Comment by nmadruga** [comment]
@adamdewey this one is only config basically. You can change on the DTAC specific snapshot by editing the action "sendNotification". I'll leave here so we can do the same on core_template snapshots too

**Comment by adamdewey** [comment]
Hey Nicole, yep thanks - I already updated my DTAC one, but yeah added it here so we remember to update the core template too!

**Comment by CarlosNZ** [comment]
Personally, I don't think the text after the greeting should start capitalised, but I see it's kind of a 50/50 thing around the place. 

But we'd expect all these messages to be customised by individual installations, anyway, so I wouldn't worry too much either way.

Added a note to  https://github.com/openmsupply/application-manager-server/issues/604, so closing this for now:
