### ISSUE TITLE
(User Registration) Misleading password validation message - 6 or 8 characters?

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/application-manager-server#599]
![image](https://user-images.githubusercontent.com/19318937/135159911-8741878c-4087-4aab-8984-7a8a7f19d4a3.png)

**Comment by nmadruga** [comment]
Oh! I see why I was missing this ones -> it's not using the Project to show on our board.

Please @adamdewey when adding next issues use our [board](https://github.com/orgs/openmsupply/projects/6):
1. create a note on column "Sprint to do"
2. convert note to issue - you would have to select web-app or server. But whatever one works

If you prefer to create straight as an issue, remeber to select the project on the right side =>

Just need to do this:
<img width="326" alt="Screen Shot 2021-09-29 at 8 25 39 PM" src="https://user-images.githubusercontent.com/16461988/135222388-7b89af6a-c5ed-45e5-a59a-45a7ecd9a2d0.png">

**Comment by adamdewey** [comment]
Oh sorry @nmadruga! Will know for next time :)

**Comment by nmadruga** [comment]
@adamdewey just checking one thing. This was presented in the Scholarship snapshot. I can fix this in our `core_templates` so next time we use this as a base will have this fix. But can you also make this on the Scholarship one, or could you point me the direction where this is running and I will also make the change there?

**Comment by adamdewey** [comment]
Thanks @nmadruga - I think I've already made the changes to the Scholarship snapshot! Maybe you have an older version? Cheers :)

**Comment by CarlosNZ** [comment]
We can close this as an issue -- it's listed in https://github.com/openmsupply/application-manager-server/issues/604
