### ISSUE TITLE
(Ongoing) documentation of question type parameters

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#61]
**NOTE: Please keep this spec updated in the documentation.** Wiki page: https://github.com/openmsupply/application-manager-web-app/wiki/Element-Type-Specs

Let's use this post to start an authoritative description of `template_element` fields, and the input and response parameters of each question/element type, so we can be confident we're naming and defining things correctly when working on different areas.

I'd suggest that as each plugin is implemented, we add its spec to a wiki page and make further updates there. 

For now, let's only add the question types that we're planning on implementing initially?

----

## Template Element fields
- **id, section_id** : database references
- **code**: `string` -- unique (per template) identifier
- **index**: `integer` -- element ordering sequence (starting at `0`)
- **title**: `string` -- describes the element, shown in template builder (probably)
- **category**: `enum` -- either "Information" or "Question"
- **visibility_condition**: `JSON` -- dynamic query determining whether element appears to the user
   - default: `{"value": true}` (i.e. it always appears) _--We should add this as a PostGres default so it doesn't need to be provided in templates (remove this comment when done)_
- **element_type_plugin_code**: `string` -- code of the question/element plugin that presents this element to the UI
- **is_required**: `JSON` -- dynamic query determining whether question is required to be answered _(Currently it is `boolean` -- we should change this to dynamic field)_
   - default: `{"value": true}`  _--TO-DO: Add default to database schema_
- **is_editable**: `JSON` -- dynamic query determining whether can be edited (Would only be false in rare circumstances)
   - default: `{"value": true}`  _--TO-DO: Add default to database schema_
- **parameters**: `JSON` -- the parameters specific to each question/element type. See individual plugins below for parameter breakdown
- **default_value**: `JSON` -- _TO-DO: Remove this field and use in `parameters` if required_ 
- **validation**: `JSON` -- a dynamic expression for checking if the user's response is a valid input.
   - default: `{"value": true}`  _--TO-DO: Add default to database schema_
- **validation_message**: `string` -- the message that shows in the UI when validation fails. _TO-DO: Add field to schema_

## Question/Element types

**Note**: all parameter fields can also have a dynamic query object instead of a primitive. The `evaluateExpression` function will return literal strings (or numbers, booleans) as is. The types described for the parameters below are the type that is expected to be _returned_ from a query expression.

### Short Text Input _(not yet implemented -- highest priority)_
- **type/code**: `shortText`
- **category**: `Question`

_Free-form, single-line text input element_

#### Input parameters (in the `parameters` JSON)
- **label**: `string` -- Text that shows in the HTML "label" attribute of the form element (suggestion: make this interpret Markdown)
- **description**: `string` -- additional explanatory text (usually not required) [Optional]
- **placeholder**: `string`-- text to display before user input (HTML "placeholder" attribute) [Optional]
- **maskedInput**: `boolean` -- if `true`, displays user input as masked (hidden) characters -- i.e. for passwords. [Optional]
- **minWidth**/**maxWidth**: `integer` -- optional controls over visual display [Optional] _(We may never use these)_

#### Response type
_This describes the expected object that will be stored in the `application_response` table `value` field. from the user's response_
`{ text: <string> }`

---

### Text Information _(not yet implemented)_
- **type/code**: `textInfo`
- **category**: `Information`

_For displaying blocks of text in the application_

#### Input parameters
- **title**: `string` -- Heading text to display [Optional]
- **text**: `string` -- body text to display 
_(Maybe have some formatting options, but not initially, although `text` should support Markdown)_

---

### Radio Buttons _(not yet implemented)_
- **type/code**: `radioChoice`
- **category**: `Question`

_Multi-choice question, with one allowed selection, displayed as labelled radio buttons_

#### Input parameters
- **label**: `string` -- as above
- **description**: `string` -- as above [Optional]
- **options**: `array[string]` -- the options for the radio buttons
- **default**: `string`/`number` -- the value initially selected before user input. If `number`, refers to the index of the options array. If not provided, no options will be pre-selected.
- **hasOther**: `boolean` -- if `true`, an additional text-entry field is provided so the user can add their own alternative option _(may not implement in first iteration but good to have the option in future)_

#### Response type
```
{ 
  optionIndex: <integer> (index from the options array)
  text: <string> (actual text from options array)
  reference?: To-do: some way to link the response to an entity in database (e.g. an organisation)
  -- @nmadruga maybe you have an idea of what we'd need here
}

```

---

### Drop-down Selector _(not yet implemented)_
- **type/code**: `dropdownChoice`
- **category**: `Question`

_Multi-choice question, with one allowed option, displayed as Drop-down list (Combo-box)_

#### Input parameters
- **label**: `string` -- as above
- **description**: `string` -- as above [Optional]
- **options**: `array[string]` -- as above
- **default**: `string`/`number` -- if not provided, defaults to index 0.

#### Response type
```
{ 
  optionIndex: <integer> (index from the options array)
  text: <string> (actual text from options array)
  reference?: To-do -- as above
}

```

---

### Page Break _(not yet implemented)_
- **type/code**: `pageBreak`
- **category**: `Information`

_For specifying where the list of questions is broken into UI pages/steps. The **previous** question of this element will be the **last** element on a page_

#### Input parameters
- **pageBreakValidityCheck**: `boolean` -- If `true`, the user cannot proceed to the next page unless _all_ questions on the current page have passed validation
   - default: `false`

**Comment by andreievg** [comment]
Was wondering about category. I thought it would be used to distinguish between special element types like page break and grouping vs plugin elements.

**Comment by andreievg** [comment]
on second thought, being able to distinguish between 'informative' and 'question' would be usefully for changing template config ui (i.e. isEditable, isRequired etc.. don't need to be configured

**Comment by CarlosNZ** [comment]
> on second thought, being able to distinguish between 'informative' and 'question' would be usefully for changing template config ui (i.e. isEditable, isRequired etc.. don't need to be configured

So that's how it is now -- `category` just distinguishes between **Question** and **Information** types.

**Comment by CarlosNZ** [comment]
Additional comment from @andreievg -- `template_element` field needs a `validation_message` field, for what to present to the user when their entry is invalid. 

Since we don't have a way to distinguish between different types of validation failure with a query, the message should cover all options. For example:

> Email is invalid. You must not use an email that already exists in the system, and it must be formatted correctly.

Updated original post.

**Comment by CarlosNZ** [comment]
This now has a [documentation/wiki page](https://github.com/openmsupply/application-manager-web-app/wiki/Element-Type-Specs) -- so let's use that as primary reference (always updated when changes are made) and close this issue?

**Comment by nmadruga** [comment]
Hmm I believe this issue has been hanging in here for too long. We are probably done with it. Can I closed this @andreievg @CarlosNZ ?

**Comment by CarlosNZ** [comment]
> Hmm I believe this issue has been hanging in here for too long. We are probably done with it. Can I closed this @andreievg @CarlosNZ ?

Yeah sure, I'm keeping the element specs up to date as I go.
