### ISSUE TITLE
Bug: Failed verification code with underscore at last character.

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#620]
When clicked the link on email it didn't add the _ and the link was failing. Copy and paste worked: http://localhost:3000/verify?uid=AiQfv12pBEE23gUTX3lfYMP_

**Comment by CarlosNZ** [comment]
Ah, good catch, although this is actually an issue with specific email client's parsing on plain text links, as the template doesn't currently specify it as a link. It was fine in the email client when sending that link as plain text from Gmail web app to Apple Mail, for example.

Simplest immediate fix would be to just update the "send Email" action in the template to wrap the url in actual markdown link tags.

**Comment by CarlosNZ** [comment]
> Simplest immediate fix would be to just update the "send Email" action in the template to wrap the url in actual markdown link tags.

Although that will need me to finally fix this: https://github.com/openmsupply/application-manager-server/issues/423

**Comment by CarlosNZ** [comment]
Okay, with [this fix](https://github.com/openmsupply/application-manager-server/pull/624), this problem can be resolved just making the verification link an actual Markdown link, rather than leaving it to email clients to automatically parse.

So instead of:
```
Hi %1,

please confirm your user account registration by clicking (or copy-pasting) the following link:

%2%3
```

We can use:
```

Hi %1,

please confirm your user account registration by clicking (or copy-pasting) the following link:

[%2%3](%2%3)
```

**Comment by CarlosNZ** [comment]
@nmadruga -- are you happy with this solution? If so, we just need to update the core templates then we can close this.

**Comment by nmadruga** [comment]
> are you happy with this solution? If so, we just need to update the core templates then we can close this

Yes. I think that's a good solution for now. We need to keep the loop of wuick fixes for best results. So looks great. 

- Nice if you can add this to all templates in `core_templates`
- Add a note about this on the Template Builder docs - looks pretty empty now, but I think we need to start writing this small tips to help when we finally write the full on documentation for it.
