### ISSUE TITLE
New endpoint to list which permissions are granted to a specific user and all permissions associated to templates for a company

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#626]
## Brief

New authenticated endpoint to be used in Template to list user's permissions on a given company (FDA company to start with).
#### User Permissions

GET: `/user-permissions?username=<username>&orgId=<orgId>`

End point to get **another** user's granted permissions + all existing permissions on templates for a given organisation. If no orgId is received will list user-only permissions (the ones with organisation_id = NULL) for external users. Intended for use in template to view/edit antoher user's permissions -- client supplies `username`, `orgId` and the JWT from `/login` return

Returns (on success):

- template permissions for organisation (using `is_system_org` to filter internal/external permissionNames)
  - display_name (just the **name** field written with spaces)
  - name (to be used in the action to be granting the user's permission)
  - description (new field)
- granted permissions to user
  - Permissions names

##### RESPONSE Body (example):

```JSON
{
    "templatePermissions": 
    [
        {
            "name": "applyTestRego",
            "display_name": "Apply Test Rego",
            "description": "Permission for external user to apply for a Test template of user registration"
        },
        {
            "name": "applyCompanyRegistration",
            "display_name": "Apply Company Registration",
            "description": "Permission for external user to apply for Company registration template"
        }
    ],
   "grantedPermissions":
   [
      "applyTestRego"
   ]
}
```

## Motivation

There are some reasons of using a a new endpoint instead of GraphQL query to retrieve both lists of:
* All permissions associated to templates for company
* existing permissions associated to user

We would like that the endpoint to do some extra logic:
* If no company is given it would return all template permissions for an external user not associated to an organisation
* If the company given has the flag `is_system_org` then only list permission names with `is_system_org_permission`
  * otherwise it would list only permissions with the flat set to FALSE (which will be the default)
* Parsed response to return one list of objects of existing permissions with: **name**, **display_name** (same as name with added spaces), **description** (new field), **is_granted_user** (true/false)

### Later - create another issue
Which permissions are linked to each template/user should be only visible to a certain group of people so adding some row-level permissions to the user who is querying this (by checking their JWT), should be done in the database layer, so if no permissions are existing to the querying user the list of permissions would return empty.

**Comment by nmadruga** [comment]
Also - to be done as part of this issue #652 basically we would keep the **name** field as it is, just using the conversion done in the Endpoint to display it nicely with spaces and add 2 new fields to the **permissionName** table:
- `description` (String)
- `is_system_org_permission` (Boolean) - Default: FALSE

Then add all the ones that are meant to be only associated to internal users (e.g. Assign/Review permissions, and all Apply permissions for internal templates) snapshot to have `is_system_org_permission` as TRUE.

**Comment by CarlosNZ** [comment]
Cool, looks good. Couple of initial comments:

- don't think you need `success: true` in response. We don't do this for other endpoints, and we know if it's successful or not by whether the response is HTTP 200 or error.
- with the returned permissions, I think you'll find it way easier to deal with in the template if you separate them into "currentPermissions" and "availablePermissions", rather than just using the "isGranted" field on a single list. The evaluator can't really filter a single array based on criteria, two separate lists will be much easier. (i.e. let the server do the filtering)

Also, when you make the PR for this, can you also supply a Postman collection for testing? Thanks.

**Comment by nmadruga** [comment]
> * don't think you need `success: true` in response. We don't do this for other endpoints, and we know if it's successful or not by whether the response is HTTP 200 or error.

Thanks, will remove from the description

> * with the returned permissions, I think you'll find it way easier to deal with in the template if you separate them into "currentPermissions" and "availablePermissions", rather than just using the "isGranted" field on a single list. The evaluator can't really filter a single array based on criteria, two separate lists will be much easier. (i.e. let the server do the filtering)

Oh, ok... Not sure exacly how to use this to show the checkboxes as selected for the ones returned in available permissions. But since you are saying it would be complicated to pass a field to be used as the selector (is_granted_user) I will see how this can be done.

> Also, when you make the PR for this, can you also supply a Postman collection for testing? Thanks.

Yep. I'll post the one that I'm using

**Comment by CarlosNZ** [comment]
> Oh, ok... Not sure exacly how to use this to show the checkboxes as selected for the ones returned in available permissions. But since you are saying it would be complicated to pass a field to be used as the selector (is_granted_user) I will see how this can be done.

Check the existing "grantPermissions" for how to turn the query into checkboxes. 
You can pass a property to show, but that extracts *all* instances of that property, you can't easily filter by it.

So in the first area (display existing properties), you'd query the endpoint, and just use the "currentPermissions" property to display the permissions. Actually, it might be tricky to iterate over an array to turn it into a static text Markdown, so maybe it might be a good idea to also return "currentPermissions" as "currentPermissionsText" as well, which would be a pre-formatted Markdown string of all permissions.

And in the second part (select permissions checkboxes), you'd make the same query, but use the "availablePermissions" to populate the checkboxes.

**Comment by CarlosNZ** [comment]
I see you've updated the response shape. Just want to clarify that the templatePermissions needs to be "availablePermissions" -- i.e. all permissions WITHOUT the ones the user already has. Since we're making a new endpoint, you'll want to offload as much logic as possible to the server to make the front-end evaluator expressions simpler.

Maybe just do both, so you have the complete set available for other purposes.

So your response would have something like:
```
{
 templatePermissions: ....
 grantedPermissions: ...
 availablePermissions ..(templatePermissions minus grantedPermissions)
 permissionsText: {
   all: <Markdown list>
   granted: <Markdown list>
   available: <Markdown list>
  }
}
```
