### ISSUE TITLE
External user registration - Template basics

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#685]
### **User registers in the system - U1**

**User story:**
Only external users, no review method - simple method for a user to join the system. 

Step 1: Internal user navigates to Conforma. User selects ‘create new user’ which takes them to the form: User registration (Eng)/ and fills out form with applicant details
Step 2: User receives email verification link
Step 3: User confirms link and is now able to log into the system. Would be good if the user receives an email to confirm this.

_Granted permissions:_ User should now be able to access templates U2 & U3. 

**Template information:**
Template/Form name - User registration (Eng)/ Cadastro de usuário (Prtgs)
Section name - User information (Eng)/ Informação do usuário (Prtgs)
Template introductory text - English: ARMED Online Services Registration Form - Portuguese: Formulário de registro de serviços online

After submission page:
English: Thanks. Please check your email to verify your registration.
Portuguese:  Obrigado. Por favor, verifique seu e-mail para verificar seu registro.

**Comment by nmadruga** [comment]
> _Granted permissions:_ User should now be able to access templates U2 & U3.

Have granted permission to `applyGeneral` and will associate this permission to apply for templates U2 and U3 after finished with this setup.

**Comment by nmadruga** [comment]
> Would be good if the user receives an email to confirm this.

Not sure if this can be done. I'll put this on hold for now.

**Comment by CarlosNZ** [comment]
> > Would be good if the user receives an email to confirm this.
> 
> Not sure if this can be done. I'll put this on hold for now.

This should be pretty easy to do -- just add another notification action in the "ON VERIFICATION" section?

**Comment by nmadruga** [comment]
> > > Would be good if the user receives an email to confirm this.
> > 
> > 
> > Not sure if this can be done. I'll put this on hold for now.
> 
> This should be pretty easy to do -- just add another notification action in the "ON VERIFICATION" section?

Yes! I'm actually working on it right now : )

Also trying to check if possible to use an array for recipients as Jess required (for future envisioned work).

**Comment by CarlosNZ** [comment]
> Also trying to check if possible to use an array for recipients as Jess required (for future envisioned work).

Yes! https://github.com/openmsupply/application-manager-server/wiki/List-of-Action-plugins#send-notification
<img width="913" alt="Screen Shot 2022-03-31 at 12 26 09 PM" src="https://user-images.githubusercontent.com/5456533/160946941-2f80e412-8495-4616-aca0-2a8446bd3723.png">
