### ISSUE TITLE
External user registration - Template fields

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#686]

**Comment by jagoje** [comment]
Note: All fields mandatory 

_Note from Jess: will update Portuguese fields shortly_

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-b05cde43-7fff-5f1b-e625-1c7b71d631a2"><div dir="ltr" style="margin-left:-59.25pt;" align="left">

No# (just for ordering) | Field name (English) | Field name (Portuguese) | Description of field | Specific Field validation?
-- | -- | -- | -- | --
1 | First name |   | Free text | No
2 | Last name |   | Free text | No
3 | Email |   | Same as the existing one with the validation. | Yes. English: Not a valid email addressPortuguese:        Q: Is there a check we can include for checking for duplicate emails so people don’t have multiple accounts.
4 | Phone number |   | Free text | No
5 | Street address |   | Free text | No
6 | Town |   | Free text | No
7 | Country |   | Drop down list with single country: Angola | This should only allow Angola for now.
6 | Select a username |   | Free text | Yes. English: Must be a least 8 letters. Portuguese:
7 | Select a password |   | Free text with validation. | English: Password must be 8 characters long, include a mix of upper and lowercase characters and a number/special character. Portuguese:

</div></b>

**Comment by nmadruga** [comment]
> Q: Is there a check we can include for checking for duplicate emails so people don’t have multiple accounts.

**Comment by nmadruga** [comment]
> 6	Town	Cidade	Free text	No

@jagoje Updated to `Province` to match fields expected in the next template U2
