### ISSUE TITLE
External user registration - Email templates

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#688]

**Comment by jagoje** [comment]
### Emails for workflow U1 - External user registration 

_Note: [ - ] represent fields coming from Conforma_
_English (only for reference purposes - please user Portuguese template_

---------------------------

**Email 1: Email regarding verification link**

**English**

Dear [First name] [Last name],

To activate your account, please click on the link below to verify your email address.

Once activated you will have access to the ARMED online services portal to submit relevant applications. 

Kind regards, 
Agência Reguladora de Medicamentos e Tecnologias de Saúde


**Portuguese  (Nicole please check)**
Caro [Nome] [Sobrenome],

Para ativar sua conta, clique no link abaixo para verificar seu endereço de e-mail.

Uma vez ativado, terá acesso ao portal de serviços online da ARMED para submeter as candidaturas relevantes.

Atenciosamente,
Agência Reguladora de Medicamentos e Tecnologias de Saúde

---------------

**Email 2: Email to confirm successful registration**

English
Dear [First name] [Last name],

Thank you for registering with the ARMED online services portal. 

Your registration details are as follows:
Name: [First name] [Last name]
Email: [Email]
Phone: [Phone]
Username: [Username]

Kind regards, 
Agência Reguladora de Medicamentos e Tecnologias de Saúde



**Portuguese  (Nicole please check)**
Caro [Nome] [Sobrenome],

Obrigado por se registrar no portal de serviços online da ARMED.

Seus dados de registro são os seguintes:
Nome: [First name] [Last name]
Email: [Email]
Número de telefone: [Phone]
Nome do usuário: [Username]

Atenciosamente,
Agência Reguladora de Medicamentos e Tecnologias de Saúde

**Comment by nmadruga** [comment]
> Email 1: Email regarding verification link

@jagoje 

Which could be subtitle? I thought to add in Portuguese this:
"Verificação de usuário"

**Comment by jagoje** [comment]
> > Email 1: Email regarding verification link
> 
> @jagoje
> 
> Which could be subject? I thought to add in Portuguese this: "Verificação de usuário"

Oh yes that would be a good subject :)

**Comment by nmadruga** [comment]
Also, should I keep using the `fromEmail` field (which is displayed in the email) as: `no-reply@sussol.net` or do we want to use something which is linked to msupply.foundation or even their own organisation?

**Comment by jagoje** [comment]
I would assume that we would want to update with their own organisation.

Is this something that can be done later?

I think it is good to keep it as ***@***.*** for now :)

**Comment by nmadruga** [comment]
> I think it is good to keep it as ***@***.*** for now :)

I tried this, and it's not allowed. I'll add as `no-reply@msupply.foundation` and ask Nick to create one for us maybe
