### ISSUE TITLE
New company registration - Email templates

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#690]

**Comment by jagoje** [comment]
**Email Template 1: When Business registration application is received**

_Note from Jess: Please check the Portuguese looks ok!. I am also unsure if pictures can go in emails - if so can we move the name of the MOH/ARMED bit to below the date._

![image](https://user-images.githubusercontent.com/88009219/159615802-42037aca-25b9-41d6-bbad-dc19e88a7a08.png)
[Email template 1.docx](https://github.com/openmsupply/application-manager-server/files/8329385/Email.template.1.docx)

**Comment by CarlosNZ** [comment]
> _I am also unsure if pictures can go in emails._

In theory, yes, but it would be quite tricky to do. Emails can have some limited (Markdown) formatting, but it's not intended for fully formatted document. This looks more like what we'd attach as a PDF.

**Comment by jagoje** [comment]
> > _I am also unsure if pictures can go in emails._
> 
> In theory, yes, but it would be quite tricky to do. Emails can have some limited (Markdown) formatting, but it's not intended for fully formatted document. This looks more like what we'd attach as a PDF.

Thanks Carl, that makes sense. I have updated my post. And I can do some markdown to the text in the template if this is accessible in the template builder :)

**Comment by jagoje** [comment]
### Email template 2: If the application is sent back for amendment

![image](https://user-images.githubusercontent.com/88009219/159619300-119d5b87-6c06-4f05-af8a-5345abcb5527.png)

[Email template 2.docx](https://github.com/openmsupply/application-manager-server/files/8329525/Email.template.2.docx)

**Comment by jagoje** [comment]
### Email template 3: If company registration was approved
[Email template 3.docx](https://github.com/openmsupply/application-manager-server/files/8336661/Email.template.3.docx)


![image](https://user-images.githubusercontent.com/88009219/159794580-e9ef5d9b-6024-4a09-b23d-4ffb1bf734cf.png)

**Comment by nmadruga** [comment]
@jagoje we don't have a **Rejection** email template yet! For now that's what I have added in the U2 - Template:

**Message title**: SOLICITAÇÃO DE REGISTRO DE EMPRESA
**Message Body**:
[FirstName] [LastName],

Os nossos melhores cumprimentos.

Após a avaliação da documentação apresentada por você em relação a emrpesa abaixo indicada, sua inscrição foi **rejeitada**.

N. de Processo: [Application Serial] 
Nome da empresa: [Company name]
Data de rejeição: [Date of rejectioin]

Caso ainda seja necessário o registro da empre favor aplicar novamente.

Sem mais outro assunto de momento, queira aceitar Cordiais Saudações,

[TODO: Date email is generated]

REPÚBLICA DE ANGOLA MINITÉRIO DA SAÚDE AGÊNCIA REGULADORA DE MEDICAMENTOS E TECNOLOGIAS DE SAÚDE DEPARTAMENTO DE MEDICAMENTOS E TECNOLOGIAS DE SAÚDE SECCÃO DE REGISTRO DE MEDICAMENTOS

**Comment by nmadruga** [comment]
@jagoje Something else - I had been using the subject for all email templates as SOLICITAÇÃO DE REGISTRO DE EMPRESA, but now I notice you also added one specific SUBJECT in each template... Not sure which one to use, I imagine the one that you defined in the subject? Maybe the part with ASSUNTO: SOLICITAÇÃO DE REGISTRO DE EMPRESA should be inside the body?

**Comment by nmadruga** [comment]
> ### Email template 2: If the application is sent back for amendment
> ![image](https://user-images.githubusercontent.com/88009219/159619300-119d5b87-6c06-4f05-af8a-5345abcb5527.png)
> 
> [Email template 2.docx](https://github.com/openmsupply/application-manager-server/files/8329525/Email.template.2.docx)

A few changes after reviewing the text on the message of this email Template. Current message was updated to:

ASSUNTO: SOLICITAÇÃO DE REGISTRO DE EMPRESA
[FirstName] [LastName],

Os nossos melhores cumprimentos.

Após a avaliação da documentação apresentada por você, foram encontradas falhas ou imprecisões que requerem a sua atenção.

Para ver os problemas e fazer as alterações em sua aplicação no sistema eletrônico visite:

http://localhost:3000/application/ORG-0001

Assim, viemos por este meio solicitar a correcção do vosso formulário como solicitado, no prazo de 10 dias úteis.

É importante notar que após o final do prazo acima definido, caso não tiver sido obtida qualquer resposta da vossa parte, será proposto o indeferimento do vosso pedido com base na insuficiência de dados apresentados.

Sem mais outro assunto de momento, queira aceitar Cordiais Saudações,

[TODO: Date email is generated]

REPÚBLICA DE ANGOLA
MINITÉRIO DA SAÚDE
AGÊNCIA REGULADORA DE MEDICAMENTOS E TECNOLOGIAS DE SAÚDE
DEPARTAMENTO DE MEDICAMENTOS E TECNOLOGIAS DE SAÚDE
SECCÃO DE REGISTRO DE MEDICAMENTOS
