### ISSUE TITLE
Registered Businesses - Outcome table

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#691]

**Comment by jagoje** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-c3c7aa73-7fff-c18b-09e7-12ef7c27744e"><p dir="ltr" style="line-height:1.2;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Outcome Table:</span></p><p dir="ltr" style="line-height:1.2;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Title: Registered companies</span></p><p dir="ltr" style="line-height:1.2;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Accessible by: All internal users. External user should be able to access the information about companies that are members of.</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

English table column titles
--
Company ID (assigned by system) | Company name | Company address (Street) | Company address (Province) | Company address (Country) | Company type

</div></b>

**Comment by nmadruga** [comment]
### Portuguese table column titles
Company ID (assigned by system) | Company name | Company address (Street) | Company address (Province) | Company address (Country) | Company type
| -- | -- | -- | -- | -- | -- |
| ID empresa | Nome da empresa | Endereço | Província | País | Tipo de empresa
