### ISSUE TITLE
New company registration - Template basics

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#692]

**Comment by jagoje** [comment]
### User applies to register a new company - U2
**User story:**
Only external users, single review level by ARMED

Step 1: User starts application to register a new business.
Step 2: For the fields business name and business address, the system should cross check that these are not existing in the system. If they are existing, warning text should appear to prompt the applicant to submit a ‘join business application’.
Step 3: Applicant continues to fill out the application form.
Step 4: The applicant submits the application and receives a confirmation email (template provided) 
Step 5: ARMED staff member with permission to approve business applications are able to ‘self-assign’ application.
Step 6: ARMED staff member reviews the application. The outcomes are:
Approve - Email sent, company is registered with applicant as a member, this information is included in the outcome table.
Reject - Email sent, company is not registered, no information is included in the outcome table.
Send request for information to applicant - Email sent to applicant, applicant is able to log in and amend application, application is resubmitted to the assigned reviewer for continued evaluation.

Granted permissions: User should now be added to the company and able to access template P1.

**Template information:**
Template/Form name - Novo registro comercial
Section name/s - Section 1:Informações da Empresa

<img width="299" alt="image" src="https://user-images.githubusercontent.com/88009219/159804783-362edb2d-6fe4-40a0-9e55-6d8394e44a89.png">

**Comment by nmadruga** [comment]
## Portuguese

Template name: Formulário para adicionar empresa

**Comment by nmadruga** [comment]
### Start message in portuguse

## Favor solicitar os seguintes documentos durante o registro:
- TBD

**Comment by nmadruga** [comment]
> Step 2: For the fields business name and business address, the system should cross check that these are not existing in the system. If they are existing, warning text should appear to prompt the applicant to submit a ‘join business application’.

TODO: Should use validation with endPoint checkUnique associated to existing company (external) that already have the same address

**Comment by nmadruga** [comment]
<img width="922" alt="Screen Shot 2022-04-04 at 3 35 09 PM" src="https://user-images.githubusercontent.com/16461988/161469603-f60c961c-f7e8-4fd4-9a19-1f5f04362465.png">
## Applicant

**permission**: applyGeneral

### Stage
**Name**: Aprovação, **description**: O formulário para criar novo registro deverá ser aprovado pela agência reguladora

#### Level 1
**Name**: Revisão, **permission**: reviewOrgRego, self-assignable: ✔️ 
**Assigner permission**: assignGeneral (Not required)

**Comment by nmadruga** [comment]
> Granted permissions: User should now be added to the company and able to access template P1.

Missing doing that. Need to know which one is P1 and how we are going to name its permission : )
