### ISSUE TITLE
New company registration - Template fields

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#693]

**Comment by jagoje** [comment]
### New company registration U2 - Template fields

**Page: 1**
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-a60d67e8-7fff-3c52-0a01-38db01ad0995"><div dir="ltr" style="margin-left:-59.25pt;" align="left">

No# (just for ordering) | Field name (English) | Field name (Portuguese) | Description of field | Specific Field validation?
-- | -- | -- | -- | --
1 | Company information | Informações da Empresa | Text field above the form fields | NA
2 | Name of company | Nome da empresa | Text field | Yes should only allow unique names not already in the database. This is ok to show applicant similar names after typing the first few letters.If name matches a text warning should appear prompting to applicant to ensure the company is not registered in the system.
3 | Company type | Tipo de companhia | Drop down: WholesalerManufacturerImporterOther (allow free text if seleceted) | NA
4 | Company physical address | Endereço físico da empresa | Text field above the form fields | NAText next to form fields:Os detalhes inseridos aqui devem corresponder aos documentos emitidos pelo órgão regulador em sua jurisdição. Você anexará evidências desses documentos na seção a seguir.
5 | Country | País | Drop down list (Full country names) | NA
6 | Province | Província | Drop down list | NA
7 | Street Address | Endereço | Free text | NA
8 | Is the postal address the same as the physical address? | O endereço postal é diferente do endereço físico? | Check box:Yes, No | If yes - the postal address fields should fill with the information provided in the physical address section and not editable.  If no - the postal address fields should appear empty and allow  for editing.
9 | Company postal address | Endereço postal da empresa | Text field above the form fields | NA
10 | Country | País | Drop down list (Full country names) | NA
11 | Province | Província | Drop down list | NA
12 | Street Address | Endereço | Free text | NA

</div></b>

**Comment by jagoje** [comment]
### Section 2:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-593ff602-7fff-9072-da6c-ba03e20c2ee3"><div dir="ltr" style="margin-left:-59.25pt;" align="left">

No# (just for ordering) | Field name (English) | Field name (Portuguese) | Description of field | Specific Field validation?
-- | -- | -- | -- | --
1 | Local Agent Information | Informações do agente local | Text field above the form fields | NA
2 | First name | Primeiro nome | Should be pre-filled from user details and non-editable |  
3 | Last name | Sobrenome | Should be pre-filled from user details and non-editable |  
4 | Email | Email | Should be pre-filled from user details and non-editable |  
5 | Phone number | Número de telefone | Should be pre-filled from user details and non-editable |  
6 | Street address | Endereço | Should be pre-filled from user details and non-editable |  
7 | Province | Província | Should be pre-filled from user details and non-editable |  
8 | Country | País | Should be pre-filled from user details and non-editable |  
9 | Company contact | contato da empresa | Text field above the form fields |  
10 | Name | Nome | Free text | NA - can appear in a table with fields (10-12 if easier)
11 | Role | Função | Free text | NA - can appear in a table with fields (10-12 if easier)
12 | Email | Email | Free text | NA - can appear in a table with fields (10-12 if easier)
13 | Phone number | Número de telefone | Free text | NA - can appear in a table with fields (10-12 if easier)

</div></b>

**Comment by jagoje** [comment]
### Section 3:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-f76a1357-7fff-38b0-b199-87e9c2ff681e"><div dir="ltr" style="margin-left:-59.25pt;" align="left">

No# (just for ordering) | Field name (English) | Field name (Portuguese) | Description of field | Specific Field validation?
-- | -- | -- | -- | --
1 | Application payment receipt | Comprovativo do pagamento da taxa | PDF/Word file upload | NA
2 | Letter of authorization from the principal company | Carta de autorização da empresa principal | PDF/Word file upload | NA
3 | Proof of your company registration | Comprovante de registro da sua empresa | PDF/Word file upload | NA
4 | ID of local agent | ID do agente local | PNG/JPG/PDF | NA

</div></b>

**Comment by jagoje** [comment]
Section 4:

Declaration:

I confirm and declare that:

- [ ] The information contained in this application is true and correct;

- [ ] This form has been completed by the applicant identified above.

**Comment by nmadruga** [comment]
> 6 | Province | Província | Drop down list | NA |

We don't have a way of generating a list based on what is selected in another field yet.
What can be done here is: Show the list of Angola provinces enable for selction **IF** they select Angola on the Country option

**Comment by CarlosNZ** [comment]
> We don't have a way of generating a list based on what is selected in another field yet.

Yes we do, don't we? Can you give an example of what you'd like it to do?

**Comment by nmadruga** [comment]
Well - it just seems a lot of work anyway and I don't think this is relevant - only for provinces in Angola

BTW I'm looking for an API to get the Angola list of provinces now

**Comment by nmadruga** [comment]
> 8 | Is the postal address the same as the physical address? | O endereço postal é diferente do endereço físico? | Check box:Yes, No | If yes - the postal address fields should fill with the information provided in the physical address section and not editable.  If no - the postal address fields should appear empty and allow  for editing.

@jagoje  I have hidden the fields for postal address in case the option Yes is selected

**Comment by nmadruga** [comment]
Also pending, making sure that all these have been marked - using validation
<img width="392" alt="Screen Shot 2022-04-05 at 3 13 29 PM" src="https://user-images.githubusercontent.com/16461988/161671725-86f82675-30d5-4c61-80e1-077f5818ad4c.png">
