### ISSUE TITLE
Joining an existing company - Template basics

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#695]

**Comment by jagoje** [comment]
### External user applies to join a registered company - U3
**User story:**
Only external users, single review level by ARMED

Step 1: User starts application to join a registered business.
Step 2: The applicant searches for the name of the company. Information from the company should pre-fill.
Step 3: Applicant continues to fill out the application form.
Step 4: The applicant submits the application and receives a confirmation email (template provided)
Step 5: ARMED staff member with permission to approve business applications are able to ‘self-assign’ application.
Step 6: ARMED staff member reviews the application. The outcomes are:
Approve - Email sent, user is registered as a member, this information is included in the outcome table.
Reject - Email sent, user is not included as a member of the company, no information is included in the outcome table.
Send request for information to applicant - Email sent to applicant, applicant is able to log in and amend application, application is resubmitted to the assigned reviewer for continued evaluation.

Granted permissions: User should now be added to the company and able to access template P1.

**Template information:**
Template/Form name - Juntar-se a uma empresa registada
Section name/s
- Section 1:Informações da empresa & Pessoal da empresa
- Section 2: Documentação da empresa
- Section 3: Declaração

**Comment by nmadruga** [comment]
Template name: Formulário para junta-se a uma empresa

**Comment by nmadruga** [comment]
### Portuguese application name 
Participar de uma empresa registada

> ~~Plural name in Portuguese: Formulários para junta-se a empresas registradas~~
Plural name: Formulários para participação em empresas registadas
> 
> ### Start message in Portuguese
> ### Favor solicitar os seguintes documentos ao juntar-se a empresa:
> ~~* TBD~~
- Comprovativo do pagamento da taxa
- Carta de autorização da empresa principal
- ID do agente local

> 
> ### Submission message in Portuguese:
> Obrigado! O seu formulário foi enviado.

**Comment by nmadruga** [comment]
Almost done.... just fixing error happening on GrantPermission now.

Also - note that this template is configured as "non-interactive" so the option List os Questions isn't available for selection
