### ISSUE TITLE
Medicine registration - Template basics

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#704]

**Comment by jagoje** [comment]
Provisional medicine registration - P1
User story:

Granted permissions: 

Template information:
Template/Form name - Provisional medicine registration (Eng)/ Registros de Medicamentos (provisório) (Prtgs)
Section names: - 
Template introductory text - 

After submission page:
English: 
Portuguese:

**Comment by nmadruga** [comment]
Temp. `startMessage` and `submissionMessage` in Portuguese:

StartMessage: 
```
### Favor solicitar os seguintes documentos para o registro de medicamento:
- TBD

**O formulário enviado deverá passar por uma série de etapas que começam da aceitações do dossie para avaliação técnica pela ARMED.**

Você poderá salvar o formulário, fechar e continuar a qualquer momento antes de realizar o envio do mesmo.
```
Submission: "Obrigado! O seu formulário foi enviado."
