### ISSUE TITLE
Template - Edit User

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#714]

**Comment by nmadruga** [comment]
### Fields

**Portuguese**
<img width="723" alt="Screen Shot 2022-04-12 at 10 47 22 AM" src="https://user-images.githubusercontent.com/16461988/162845616-18fbf80d-86c3-4443-88e4-0f0a05399ac3.png">



## Stages
`Automatic`
N/A

## Permissions (apply)
`applyGeneral`

### Email send after changes

**Portuguese**

### Subject
Confirmação de edição de usuário

### Message

[FirstName] [LastName],

As alterações para o seu usuário foram salvas no portal de serviços online da ARMED.

Seus dados de registro são os seguintes:
Nome: [FirstName] [LastName]
E-mail: [Email]
Número de telefone: [Phone]
Nome do usuário: [Username]

Atenciosamente,
Agência Reguladora de Medicamentos e Tecnologias de Saúde
