### ISSUE TITLE
Document icons are not appearing

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#730]

**Comment by jagoje** [comment]
Low priority issue:

Known bug, document icons are not displaying the thumbnail

<img width="651" alt="image" src="https://user-images.githubusercontent.com/88009219/165025600-bf6c4c1f-7fc6-4e35-bb88-d05b733a082f.png">

**Comment by CarlosNZ** [comment]
These will be restored when the server restarts. When we run in development, the server restarts every time a snapshot is loaded, not sure if that happens in a production server.

**Comment by CarlosNZ** [comment]
I think I'll add to the useSnapshot script to make it run the "createFilesFolders" function at the end of a snapshot load, so it won't matter if the server restarts or not.
