### ISSUE TITLE
Create separated sql files for each table and script to import in order 

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#8]
Only for creating tables.

Goal: Having a clearer way to check for schema updates.

**Comment by CarlosNZ** [comment]
What do you mean by "a clearer way to check for schema updates"?

**Comment by CarlosNZ** [comment]
Question -- what do you guys think @andreievg @nmadruga 

There are two ways to do this:

1. Name all `.sql` scripts with a numeric prefix (e.g. `01_user_table`), then make a script to loop over all files in folder (the prefix will ensure they execute in the correct order)

2. No numeric prefix on files, but keep correct order in an array of filenames in build script.

Advantage of **1** is that any name changes only have to be done to one file, and the build script is simpler. Downside is if there are any files inserted in the middle of the sequence, all later numbers will have to be incremented (which is not really a big deal auto-renaming).

I've started with Option 1, but can easily switch to Option 2 later if you guys think that's preferable.
