### ISSUE TITLE
Action plugin - update responseMap on create user to receive code of fields to be used as output

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#93]
As discussed here:
https://github.com/openmsupply/application-manager-server/pull/91#discussion_r514574036

Currently the **createUser** action has a hardcoded map of field codes (from application)  to be output after the action runs. My suggestion was to - somehow receive this map (of typed fields - which means the fields name are still the same) and stores the map within the action to be called for a particular application template.

**Comment by nmadruga** [comment]
I don't think this is still needed. What do you think @CarlosNZ ?

**Comment by CarlosNZ** [comment]
Yeah, don't actually remember exactly what this was for. Seems completely redundant based on current functionality. Will close. 🤷‍♂️
